# ruff: noqa: E501
# Embedded HTML/CSS/JavaScript is checked through browser tests, not Python line width.
"""Browser interface for the bounded V1.5 answer-conditioned research pilot."""
HTML = r'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Life Patterns · Birth-date research test</title>
<style>
:root{font-family:system-ui,sans-serif;color:#20302c;background:#f5f6f2;line-height:1.55}*{box-sizing:border-box}body{margin:0}main{max-width:920px;margin:auto;padding:28px 20px 80px}h1{font-size:clamp(25px,4vw,36px);line-height:1.2;margin:10px 0 20px}h2{font-size:23px;margin:0 0 14px}h3{font-size:18px;margin:0 0 10px}a{color:#225749}.eyebrow{letter-spacing:.12em;text-transform:uppercase;font-size:12px}.card{background:white;border:1px solid #d5dcd6;border-radius:12px;padding:24px;margin:18px 0}.muted{color:#566660}.note{background:#eef3ee;padding:14px;border-left:3px solid #63836d}.warning{background:#fff3d5;padding:14px;border-left:3px solid #997b23}.error{color:#8a2626;white-space:pre-wrap}.status{padding:8px 0;min-height:28px}textarea,input,select,button{font:inherit}textarea,input:not([type=checkbox]),select{display:block;width:100%;padding:10px;border:1px solid #aebfb5;border-radius:6px;background:white;color:inherit}textarea{min-height:145px;resize:vertical}label{display:block;margin:10px 0}label.check{display:flex;gap:10px;align-items:flex-start}input[type=checkbox]{margin-top:6px;min-width:18px;min-height:18px}button{cursor:pointer;border:1px solid #245d49;border-radius:6px;padding:10px 18px;color:white;background:#245d49;margin:4px 6px 4px 0}button.secondary{background:white;color:#245d49}button:disabled{opacity:.5;cursor:default}.row{display:flex;gap:14px;flex-wrap:wrap}.row>*{flex:1;min-width:180px}.small{font-size:14px}.hidden{display:none!important}details{margin:12px 0}summary{cursor:pointer}blockquote{margin:12px 0;padding:8px 15px;border-left:3px solid #c6d3c9;white-space:pre-wrap}table{width:100%;border-collapse:collapse;font-size:14px}td,th{padding:8px;text-align:left;border-bottom:1px solid #dae0da}.result-number{font-size:34px;font-weight:650;line-height:1.2}.steps{display:flex;gap:12px;flex-wrap:wrap;font-size:14px;margin:18px 0}.steps span{padding:5px 12px;background:#e3ebe3;border-radius:15px}.domain{padding:20px 0;border-bottom:1px solid #dde3dd}.domain:last-child{border:0}.state-label{font-weight:600}.busy{opacity:.65;pointer-events:none}progress{width:100%;height:8px}pre{white-space:pre-wrap;word-break:break-word;font-size:13px}@media(max-width:560px){.card{padding:17px}main{padding:18px 12px 60px}}
</style></head><body><main>
<a href="/" class="small">← Existing Life Patterns interview</a>
<div class="eyebrow">Research pilot · version 1.5</div>
<h1>Do these birth-chart rules distinguish your answers?</h1>
<p>This experiment keeps six previously selected astronomical conditions fixed. It compares candidate birth times with your reviewed answers. It is <strong>not a validated personality test</strong>, and a good result is not a diagnosis or proof of astrology.</p>
<div class="steps"><span>1 · Answer or import</span><span>2 · Review meaning</span><span>3 · Freeze comparison</span><span>4 · Check documented birth</span></div>
<div class="note small">This focused pilot reuses nine scenarios from the existing interview bank, covering five interpretations used by the six conditions. It does not replace the full interview or claim to measure every trait. Several votes share the same interpretation, so they are not independent measurements.</div>
<section class="card"><h2>Your choice and privacy</h2><p id="privacy" class="small"></p>
<label class="check"><input id="consent" type="checkbox"><span>I am an adult choosing to take this research test, or I am administering it with the adult participant's informed permission. I understand it is experimental.</span></label>
<label>Prior familiarity with your own astrology chart or this test's rule meanings<select id="knowledge"><option value="unsure">Unsure</option><option value="no">No prior familiarity</option><option value="yes">Yes, some familiarity</option></select></label>
<p class="small muted">Do not enter names, contact details, or someone else's private material without their permission. Do not enter the birth date in the interview. Birth data are requested only after the answers have been reviewed and frozen.</p>
</section>
<section class="card" id="answer-section"><h2>1. Answer in your own words</h2><p id="intro" class="small"></p>
<details id="import-box"><summary>Use an existing interview instead of repeating questions</summary><p class="small">Paste relevant questions and answers from the existing survey. Keep their context, but leave out birth information and prior chart or ranking results. This supplements the scenario answers below; it does not require you to answer everything again.</p><textarea id="imported" aria-label="Existing interview" placeholder="Paste the existing interview here. Avoid birth dates and identifying details."></textarea></details>
<p id="question-count" class="eyebrow"></p><progress id="question-progress" max="9" value="1"></progress><div id="antecedent" class="note small hidden"></div>
<h3 id="question"></h3><textarea id="answer" aria-label="Your answer" placeholder="What would you usually do, feel, or notice? Conditions and exceptions are welcome. You may also say the situation does not fit."></textarea>
<div><button id="previous" class="secondary">Back</button><button id="skip" class="secondary">Skip / not applicable</button><button id="next">Next</button></div>
<p class="small muted">Answers are saved in this browser as you type. Changing them marks any previous interpretation and ranking as outdated.</p>
<button id="to-review" class="secondary">Review interpretations now</button>
</section>
<section class="card" id="review-section"><h2>2. Review what your answers mean</h2><p>The statements below are the test's <strong>explicit experimental interpretations</strong>, not established facts inferred about you. Select what you actually endorse. You can leave anything unknown or mixed. A manual choice is a new direct self-report, not proof that an earlier scenario established it.</p>
<label class="check small"><input id="model-consent" type="checkbox"><span>Optional: I agree to send my scenario answers and imported interview to the configured research model for a suggested interpretation. Only these responses and neutral definitions are sent; leave out birth/chart information.</span></label>
<button id="suggest" class="secondary">Suggest interpretations from my answers</button><p id="interpret-status" class="status" role="status"></p>
<div id="domains"></div><label class="check"><input id="reviewed" type="checkbox"><span>I have reviewed these interpretations and corrected anything that does not describe the participant. Unknown and mixed answers remain unscored.</span></label>
</section>
<section class="card" id="location-section"><h2>3. Freeze the candidate comparison</h2><p class="small">The birthplace is used to calculate each candidate chart. Do not enter the actual birth date yet. The standard test uses <strong>999 preselected decoys</strong>; your actual instant is compared later as the 1,000th candidate.</p>
<label>Birth city<input id="city" placeholder="For example: Philadelphia"></label><button id="find-place" class="secondary">Find birthplace</button><div id="places"></div>
<div class="row"><label>Latitude<input id="latitude" type="number" step="any" min="-66" max="66" placeholder="Degrees north / south"></label><label>Longitude<input id="longitude" type="number" step="any" min="-180" max="180" placeholder="Degrees east / west"></label></div>
<p class="small muted">Manual coordinates are supported. Birthplaces beyond 66° north or south are not supported in this pilot. Place lookup uses Open-Meteo / GeoNames.</p>
<label>Candidate panel<select id="panel"><option value="999">Primary: 999 decoys + actual instant</option><option value="99">Secondary: 99 decoys + actual instant</option><option value="9999">Secondary: 9,999 decoys + actual instant</option></select></label>
<p class="small">These are nested samples across August 1926–August 2026, <strong>not an exhaustive century scan</strong>. Do not select whichever panel gives the nicest result. The previously completed full-century result belongs to the original development case.</p>
<button id="run">Freeze answers and rank the panel</button><p id="run-status" class="status" role="status"></p>
</section>
<section class="card hidden" id="result-section"><h2>Frozen comparison</h2><div id="result-summary"></div><details><summary>Highest-scoring sampled candidates</summary><div id="candidate-table"></div></details><p id="fingerprints" class="small muted"></p>
<div class="warning small">The original conditions were selected using a known development case. This is a new-person test of the separately declared answer-to-rule bridge. Report misses and ties unchanged; do not retune the rules after seeing this person's birth date.</div>
<h3 style="margin-top:22px">4. Reveal the documented birth instant</h3><p class="small">This step checks the frozen result; it does not fit or choose new rules. Use the local clock time and the location's time zone. Estimated times are not evidence of exact-minute recovery.</p>
<div class="row"><label>Documented local date and time<input id="birth-local" type="datetime-local" step="1"></label><label>IANA time zone<input id="timezone" placeholder="America/New_York, Europe/Paris, UTC…"></label></div>
<div class="row"><label>Time source<select id="time-source"><option value="unknown">Unknown</option><option value="record">Birth or other contemporaneous record</option><option value="family_memory">Family memory</option><option value="estimate">Estimate</option></select></label><label>Time uncertainty in minutes<input id="uncertainty" type="number" min="0" max="720" value="0"></label></div>
<button id="check">Check this birth instant without refitting</button><p id="check-status" class="status" role="status"></p><div id="checked-result"></div>
</section>
<section class="card"><h2>Keep or remove this test</h2><button id="export" class="secondary">Export answers, interpretations and results</button><button id="erase" class="secondary">Delete this browser's test</button><p class="small muted">Export before changing devices. Older frozen results stay in the export history; they are not silently overwritten by later edits. Server-side result handles expire after two hours or a restart.</p><p id="global-status" class="status" role="status"></p></section>
</main><script>
'use strict';
const $=id=>document.getElementById(id), KEY='life-patterns-birth-test-v15';
let contract=null, revision=0, busy=false;
const fresh=()=>({answers:{},profile:{},suggestions:[],history:[],index:0,consent:false,modelConsent:false,reviewed:false,knowledge:'unsure',latitude:'',longitude:'',timezone:'',panel:999,revealed:false,resultsSeen:false,run:null,check:null});
let state=fresh();try{const old=JSON.parse(localStorage.getItem(KEY)||'null');if(old&&typeof old==='object')state={...state,...old};}catch(e){}
state.resultsSeen=Boolean(state.resultsSeen||state.run||state.history.length);
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch(e){$('global-status').textContent='Browser storage is unavailable. Export your test before leaving this page.';}}
function status(id,text,error=false){$(id).textContent=text;$(id).className='status'+(error?' error':'');}
function stable(v){if(Array.isArray(v))return '['+v.map(stable).join(',')+']';if(v&&typeof v==='object')return '{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+stable(v[k])).join(',')+'}';return JSON.stringify(v);}
async function sha(v){const bytes=new TextEncoder().encode(stable(v));const hash=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(hash)].map(n=>n.toString(16).padStart(2,'0')).join('');}
function answerRows(){const rows=contract.questions.map(q=>({question_id:q.id,text:state.answers[q.id]||''}));if(state.answers.imported)rows.push({question_id:'imported',text:state.answers.imported});return rows;}
function snapshotOld(){if(state.run){state.history.push({run:state.run,check:state.check,profile:{...(state.run.frozen_profile||state.profile)},answers:state.run.frozen_answers||null,archived_utc:new Date().toISOString()});state.run=null;state.check=null;}}
function changed(raw=false){revision++;snapshotOld();state.reviewed=false;$('reviewed').checked=false;if(raw){state.suggestions=[];if(contract)renderDomains();status('interpret-status','Answers changed. Previous classifications have not been recoded; review them again or request a new interpretation.');}save();renderResult();}
async function api(path,body,method='POST'){const response=await fetch('/birth-test/api/'+path,{method,headers:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),cache:'no-store'});let data;try{data=await response.json();}catch(e){throw new Error('The server returned an unreadable response. Your local answers were kept.');}if(!response.ok){throw new Error(typeof data.detail==='string'?data.detail:JSON.stringify(data.detail||data));}return data;}
function showQuestion(){const q=contract.questions[state.index];$('question-count').textContent='Scenario '+(state.index+1)+' of '+contract.questions.length;$('question-progress').value=state.index+1;$('question').textContent=q.question;$('answer').value=state.answers[q.id]||'';$('previous').disabled=state.index===0;$('next').textContent=state.index===contract.questions.length-1?'Continue to review':'Next';const required=q.context_sources.filter(id=>contract.questions.some(n=>n.id===id));$('antecedent').classList.toggle('hidden',required.length===0);$('antecedent').textContent=required.map(id=>{const prior=contract.questions.find(n=>n.id===id);return 'Earlier scenario: '+prior.question+'\nYour answer: '+(state.answers[id]||'Not answered; you may skip this follow-up.');}).join('\n\n');}
function renderDomains(){const box=$('domains');box.replaceChildren();for(const d of contract.domains){const section=document.createElement('div');section.className='domain';const title=document.createElement('h3');title.textContent=d.label;section.append(title);const a=document.createElement('p');a.textContent='A: '+d.affirmative;const b=document.createElement('p');b.textContent='B: '+d.negative;section.append(a,b);const limit=document.createElement('p');limit.className='small muted';limit.textContent=d.limit;section.append(limit);const suggested=state.suggestions.find(r=>r.domain_id===d.id);if(suggested){const summary=document.createElement('p');summary.className='note small';summary.textContent='Suggested interpretation — '+suggested.summary;section.append(summary);for(const source of suggested.evidence||[]){const quote=document.createElement('blockquote');quote.className='small';quote.textContent=source.question_id+': “'+source.quote+'”';section.append(quote);}}const label=document.createElement('label');label.textContent='Which description do you endorse?';const select=document.createElement('select');select.id='domain-'+d.id;for(const [value,text] of [['unknown','Unsure / not enough information'],['supported','A describes me'],['contradicted','B describes me'],['mixed','Both, or it depends in a way neither pole captures'],['not_applicable','Not applicable / prefer not to answer']]){const option=new Option(text,value);select.append(option);}select.value=state.profile[d.id]||'unknown';select.onchange=()=>{state.profile[d.id]=select.value;changed();};label.append(select);section.append(label);box.append(section);}}
function renderResult(){const result=state.run;$('result-section').classList.toggle('hidden',!result);if(!result)return;$('result-summary').replaceChildren();const line=document.createElement('p');line.textContent=result.decoy_count+' candidate times were scored with your frozen profile. '+result.maximum_observed_count+' sampled candidates share the highest score ('+result.maximum_observed_score+').';$('result-summary').append(line);if(result.answers_identical_to_all_positive_signature){const note=document.createElement('p');note.className='warning';note.textContent='Your reviewed profile activates the same positive votes as the original six-rule signature. Its ranking therefore matches the all-positive baseline; this profile does not provide a different ranking from that baseline.';$('result-summary').append(note);}if(result.result_class==='EXPLORATORY_AFTER_REVEAL'){const note=document.createElement('p');note.className='warning';note.textContent='Exploratory update: a prior ranking has already been shown in this browser. This is not an untouched first test.';$('result-summary').append(note);}const table=document.createElement('table');const head=document.createElement('tr');for(const t of ['Candidate time (UTC)','Score, not rank']){const th=document.createElement('th');th.textContent=t;head.append(th);}table.append(head);for(const r of result.top_candidates){const tr=document.createElement('tr');for(const text of [r.utc,String(r.score)]){const td=document.createElement('td');td.textContent=text;tr.append(td);}table.append(tr);}$('candidate-table').replaceChildren(table);$('fingerprints').textContent='Model '+result.model_id.slice(0,12)+' · profile '+result.profile_sha256.slice(0,12)+' · candidate panel '+result.panel_sha256.slice(0,12)+' · frozen '+result.computed_utc;renderCheck();}
function renderCheck(){const box=$('checked-result');box.replaceChildren();if(!state.check)return;const r=state.check;const p=document.createElement('p');p.className='result-number';p.textContent=r.rank_best===r.rank_worst?'Rank '+r.rank_best:'Tied positions '+r.rank_best+'–'+r.rank_worst;box.append(p);const text=document.createElement('p');text.textContent='Among '+r.comparison_count_including_checked_instant+' compared instants, '+r.higher_candidates+' score higher and '+r.tied_other_candidates+' other candidates tie. Your score is '+r.score+'. No rules were refitted.';box.append(text);const base=document.createElement('p');base.className='small';base.textContent='All-positive signature baseline: positions '+r.all_positive_baseline.rank_best+'–'+r.all_positive_baseline.rank_worst+'. This is a comparison control, not a probability.';box.append(base);const note=document.createElement('p');note.className='small muted';note.textContent=r.time_uncertainty_note+' '+(r.result_class==='EXPLORATORY_REPEAT'?'This is an exploratory repeated check.':'This was the first birth reveal for this frozen profile.');box.append(note);}
async function init(){try{const response=await fetch('/birth-test/api/contract',{cache:'no-store'});if(!response.ok)throw new Error('Test configuration could not be loaded.');contract=await response.json();if(state.bridgeHash&&state.bridgeHash!==contract.bridge_sha256){snapshotOld();state.profile={};state.suggestions=[];state.reviewed=false;status('global-status','The test version changed; review your saved answers again.');}state.bridgeHash=contract.bridge_sha256;state.contract=contract;state.index=Math.min(Math.max(Number(state.index)||0,0),contract.questions.length-1);$('privacy').textContent=contract.privacy;$('intro').textContent=contract.intro;for(const d of contract.domains)if(!state.profile[d.id])state.profile[d.id]='unknown';$('consent').checked=state.consent;$('model-consent').checked=state.modelConsent;$('reviewed').checked=state.reviewed;$('knowledge').value=state.knowledge;$('latitude').value=state.latitude;$('longitude').value=state.longitude;$('timezone').value=state.timezone;$('panel').value=String(state.panel);$('imported').value=state.answers.imported||'';showQuestion();renderDomains();renderResult();save();}catch(e){status('global-status',e.message,true);}}
$('answer').addEventListener('input',()=>{if(!contract)return;state.answers[contract.questions[state.index].id]=$('answer').value;changed(true);});$('imported').addEventListener('input',()=>{state.answers.imported=$('imported').value;changed(true);});
$('previous').onclick=()=>{if(state.index>0){state.index--;showQuestion();save();}};$('next').onclick=()=>{if(state.index<contract.questions.length-1){state.index++;showQuestion();save();}else $('review-section').scrollIntoView({behavior:'smooth'});};$('skip').onclick=()=>{state.answers[contract.questions[state.index].id]='Prefer not to answer / not applicable.';changed(true);$('next').click();showQuestion();};$('to-review').onclick=()=>$('review-section').scrollIntoView({behavior:'smooth'});
$('consent').onchange=()=>{state.consent=$('consent').checked;changed();};$('model-consent').onchange=()=>{state.modelConsent=$('model-consent').checked;save();};$('reviewed').onchange=()=>{state.reviewed=$('reviewed').checked;save();};$('knowledge').onchange=()=>{state.knowledge=$('knowledge').value;changed();};for(const key of ['latitude','longitude','timezone'])$(key).onchange=()=>{state[key]=$(key).value;if(key!=='timezone')changed();else save();};$('panel').onchange=()=>{state.panel=Number($('panel').value);changed();};
$('suggest').onclick=async()=>{if(busy)return;if(!state.consent||!state.modelConsent)return status('interpret-status','Confirm both research and optional interpretation consent first.',true);const rows=answerRows();if(!rows.some(r=>r.text.trim()))return status('interpret-status','Enter or import an answer first.',true);const rev=revision;busy=true;$('suggest').disabled=true;status('interpret-status','Requesting a source-quoted interpretation. You can keep editing; edited answers will not receive a stale result.');try{const out=await api('interpret',{consent:true,answers:rows});if(rev!==revision){status('interpret-status','Answers changed during interpretation. The old suggestion was not applied.');return;}snapshotOld();state.suggestions=out.interpretations;for(const row of out.interpretations)state.profile[row.domain_id]=row.state;state.reviewed=false;$('reviewed').checked=false;revision++;save();renderDomains();renderResult();status('interpret-status','Review every interpretation. Correct it or leave it unknown before scoring.');}catch(e){status('interpret-status',e.message+' You can still review the statements manually below.',true);}finally{busy=false;$('suggest').disabled=false;}};
$('find-place').onclick=async()=>{try{status('run-status','Looking up the city…');const response=await fetch('/birth-test/api/places?'+new URLSearchParams({q:$('city').value}));const data=await response.json();if(!response.ok)throw new Error(data.detail||'Place lookup failed');$('places').replaceChildren();for(const p of data.results){const b=document.createElement('button');b.className='secondary';b.textContent=[p.name,p.admin1,p.country].filter(Boolean).join(', ');b.onclick=()=>{state.latitude=String(p.latitude);state.longitude=String(p.longitude);state.timezone=p.timezone||'UTC';$('latitude').value=state.latitude;$('longitude').value=state.longitude;$('timezone').value=state.timezone;changed();status('run-status','Birthplace selected. Review confirmation is required after changing the location.');};$('places').append(b);}status('run-status',data.results.length?'Choose the matching location.':'No match. Try the city name alone, or enter coordinates manually.');}catch(e){status('run-status',e.message,true);}};
$('run').onclick=async()=>{if(busy)return;if(!state.consent||!state.reviewed)return status('run-status','Consent and reviewed interpretations are required.',true);if(state.latitude===''||state.longitude==='')return status('run-status','Choose the birthplace or enter its coordinates.',true);const rev=revision;busy=true;$('run').disabled=true;status('run-status','Calculating the fixed candidate panel. No birth date is used to choose or fit rules.');try{const digest=await sha(answerRows());const out=await api('run',{consent:true,reviewed:true,profile:state.profile,source_answers_sha256:digest,latitude:Number(state.latitude),longitude:Number(state.longitude),decoy_count:Number(state.panel),prior_chart_knowledge:state.knowledge,previously_revealed:Boolean(state.revealed||state.resultsSeen)});if(rev!==revision){await api('run/'+out.run_id,undefined,'DELETE');status('run-status','Inputs changed while calculating. The old result was discarded.');return;}snapshotOld();out.frozen_profile={...state.profile};out.frozen_answers=answerRows();state.run=out;state.resultsSeen=true;state.check=null;save();renderResult();status('run-status','Comparison frozen. You may now reveal the documented birth instant.');$('result-section').scrollIntoView({behavior:'smooth'});}catch(e){status('run-status',e.message,true);}finally{busy=false;$('run').disabled=false;}};
$('check').onclick=async()=>{if(busy||!state.run)return;busy=true;$('check').disabled=true;const id=state.run.run_id;status('check-status','Comparing the documented instant with the frozen panel…');try{const out=await api('check',{run_id:id,birth_local:$('birth-local').value,timezone:$('timezone').value,time_source:$('time-source').value,uncertainty_minutes:Number($('uncertainty').value)});if(!state.run||state.run.run_id!==id){status('check-status','Inputs changed; this check belongs to an older frozen result.');return;}state.revealed=true;state.check=out;save();renderCheck();status('check-status','Result recorded without changing the model.');}catch(e){status('check-status',e.message,true);}finally{busy=false;$('check').disabled=false;}};
$('export').onclick=()=>{const out={schema:'life-patterns-birth-test-export-v15',exported_utc:new Date().toISOString(),...state};const url=URL.createObjectURL(new Blob([JSON.stringify(out,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='life-patterns-birth-test-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status('global-status','Export created. It contains private answers; share it only with permission.');};
$('erase').onclick=async()=>{if(!confirm('Delete this browser’s saved test and its current server result? Exported files are not deleted.'))return;const id=state.run?.run_id;revision++;state=fresh();localStorage.removeItem(KEY);if(id){try{await api('run/'+id,undefined,'DELETE');}catch(e){}}location.reload();};
init();
</script></body></html>'''
