# ruff: noqa: E501
"""Participant-facing conversational UI for Discover Your Unique Life Patterns."""

HTML = r'''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Discover Your Unique Life Patterns</title>
<style>
:root{--ink:#20242a;--muted:#667085;--line:#d0d5dd;--soft:#f7f8fa;--accent:#315c5f;--user:#eef6f6;--ai:#f7f3eb;--good:#176b44;--warn:#8a5a00}
*{box-sizing:border-box}body{margin:0;background:#fff;color:var(--ink);font:16px/1.55 system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}main{width:min(54rem,calc(100% - 2rem));margin:2rem auto 5rem}h1{font-size:clamp(2rem,7vw,3.5rem);line-height:1.02;letter-spacing:-.04em;margin:.2rem 0 .7rem}.lede{font-size:1.1rem;color:var(--muted);max-width:46rem}.card{border:1px solid var(--line);border-radius:1rem;padding:1.1rem;margin:1rem 0;background:#fff}.soft{background:var(--soft)}label{display:block;font-weight:700;margin-top:.8rem}input,textarea,button{font:inherit;border:1px solid #98a2b3;border-radius:.55rem;padding:.72rem .8rem}input,textarea{width:100%;margin-top:.3rem}textarea{min-height:7rem;resize:vertical}button{background:var(--accent);border-color:var(--accent);color:#fff;font-weight:750;cursor:pointer}button.secondary{background:#fff;color:var(--accent)}button:disabled{opacity:.55;cursor:not-allowed}.row{display:flex;gap:.65rem;flex-wrap:wrap;align-items:center}.row button{width:auto}.check{display:grid;grid-template-columns:auto 1fr;gap:.55rem;font-weight:500;align-items:start}.check input{width:1.1rem;margin-top:.25rem}.hidden{display:none}.chat{display:grid;gap:.8rem;margin:1rem 0}.bubble{padding:.9rem 1rem;border-radius:.85rem;max-width:92%;white-space:pre-wrap}.bubble.user{background:var(--user);margin-left:auto}.bubble.ai{background:var(--ai)}.meta{font-size:.82rem;color:var(--muted);margin-bottom:.25rem}.progress-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(10rem,1fr));gap:.45rem}.progress-item{border:1px solid var(--line);border-radius:.6rem;padding:.55rem .65rem;font-size:.9rem}.status-strong{border-color:#8bc5a8}.status-developing{border-color:#dfc175}.insight{border-left:4px solid var(--accent);padding:.8rem 1rem;background:#f2f8f8;margin:.8rem 0}.saved{color:var(--good);font-size:.88rem}.error{color:#a61b1b}.note{font-size:.91rem;color:var(--muted)}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:var(--soft);padding:1rem;border-radius:.7rem}.topbar{display:flex;justify-content:space-between;gap:1rem;align-items:center;flex-wrap:wrap}.pill{font-size:.82rem;border:1px solid var(--line);border-radius:999px;padding:.25rem .6rem;color:var(--muted)}
</style>
</head>
<body><main>
<div id="intro">
<p class="pill">Private long-form behavioral interview</p>
<h1>Discover Your Unique Life Patterns</h1>
<p class="lede">Talk through real decisions, relationships, projects, conflicts and life changes. The interviewer looks for patterns, exceptions and context—not personality labels. You can pause at any time and continue later.</p>
<div class="card soft"><strong>This is designed to be useful even if every astrology or Human Design model fails.</strong><p>You can build a neutral Life Patterns Map, see strengths and friction points, identify strategies that may transfer between parts of your life, and export a compact context for future coaching tools.</p><p class="note">Voice is planned next. This first version is conversational text so we can validate the interview and recovery flow before adding audio.</p></div>
<div class="card">
<h2>Start a private interview</h2>
<label for="email">Email for pause/resume recovery</label><input id="email" type="email" autocomplete="email" placeholder="you@example.com">
<label class="check"><input id="storeConsent" type="checkbox"><span>I consent to private storage of my interview responses so I can build and resume my Life Patterns profile.</span></label>
<label class="check"><input id="llmConsent" type="checkbox"><span>I consent to my interview text being processed by the configured AI provider to conduct the interview and build my neutral Life Patterns Map. Birth/chart data are not provided to this interviewer.</span></label>
<div class="row"><button id="start">Start interview</button><button id="showRecovery" class="secondary">Resume by email</button></div><p id="startStatus" class="note"></p>
</div>
<div id="recovery" class="card hidden"><h2>Resume your interview</h2><label for="recoveryEmail">Email</label><input id="recoveryEmail" type="email"><div class="row"><button id="requestCode">Send one-time code</button></div><label for="otp">6-digit code</label><input id="otp" inputmode="numeric" maxlength="6"><div class="row"><button id="verifyCode">Resume</button><button id="cancelRecovery" class="secondary">Cancel</button></div><p id="recoveryStatus" class="note"></p></div>
</div>

<div id="interview" class="hidden">
<div class="topbar"><div><strong>Life Patterns Interview</strong><div id="saveState" class="saved">Saved</div></div><div class="row"><button id="pause" class="secondary">Pause for now</button><button id="mapButton" class="secondary hidden">Build my current map</button></div></div>
<div class="card soft"><div id="progress" class="progress-grid"></div><p id="progressNote" class="note"></p></div>
<div id="insight" class="insight hidden"></div>
<div id="chat" class="chat"></div>
<div class="card"><textarea id="message" placeholder="Tell the story in your own words. Concrete examples and exceptions are especially useful."></textarea><div class="row"><button id="send">Send</button></div><p class="note">The interviewer intentionally asks one main question at a time. It may point out differences between situations rather than trying to make you sound consistent.</p><p id="turnStatus" class="note"></p></div>
<div id="mapPanel" class="card hidden"><h2>Your current Life Patterns Map</h2><div id="mapContent"></div><div class="row"><button id="exportButton" class="secondary">Prepare coaching/export context</button></div><div id="exportPanel" class="hidden"><h3>AI coaching context</h3><pre id="coachingContext"></pre></div></div>
</div>
<script>
const storageKey='lifePatternsSessionV1';let session=null;
const $=id=>document.getElementById(id);
function setStatus(id,text,error=false){const el=$(id);el.textContent=text;el.className=error?'error':'note'}
async function api(path,options={}){const response=await fetch(path,{headers:{'content-type':'application/json',...(options.headers||{})},...options});let payload={};try{payload=await response.json()}catch{}if(!response.ok)throw new Error(payload.detail||'Request failed');return payload}
function saveSession(value){session=value;localStorage.setItem(storageKey,JSON.stringify(value))}
function addBubble(role,text){const wrap=document.createElement('div');wrap.className='bubble '+role;const meta=document.createElement('div');meta.className='meta';meta.textContent=role==='user'?'You':'Interviewer';const body=document.createElement('div');body.textContent=text;wrap.append(meta,body);$('chat').append(wrap);wrap.scrollIntoView({behavior:'smooth',block:'end'})}
function renderProgress(progress){$('progress').textContent='';for(const row of progress.areas||[]){const el=document.createElement('div');el.className='progress-item status-'+row.status;el.textContent=row.label+': '+(row.status==='strong'?'strong coverage':row.status==='developing'?'developing':'not started');$('progress').append(el)}$('progressNote').textContent=(progress.episode_count||0)+' evidence-linked episodes saved. Progress describes evidence coverage; it is not a required question count.';if((progress.episode_count||0)>=2)$('mapButton').classList.remove('hidden')}
function enterInterview(payload){$('intro').classList.add('hidden');$('interview').classList.remove('hidden');$('chat').textContent='';for(const turn of payload.conversation_turns||[])addBubble(turn.role==='user'?'user':'ai',turn.text);if(!(payload.conversation_turns||[]).length)addBubble('ai','Let’s begin with a real experience rather than a personality label. Think of a consequential decision or turning point that still feels revealing. What was happening, what options were actually available, and how did you move from first reaction to commitment?');renderProgress(payload.progress);if(payload.life_patterns_map)renderMap(payload.life_patterns_map)}
async function loadCurrent(){if(!session)return;try{const payload=await api(`/api/life-patterns/interview/sessions/${encodeURIComponent(session.session_id)}?token=${encodeURIComponent(session.resume_token)}`);enterInterview(payload)}catch{localStorage.removeItem(storageKey);session=null}}
$('start').onclick=async()=>{try{setStatus('startStatus','Creating your private interview…');const payload=await api('/api/life-patterns/interview/sessions',{method:'POST',body:JSON.stringify({email:$('email').value,consent_to_store_responses:$('storeConsent').checked,consent_to_llm_processing:$('llmConsent').checked})});saveSession({session_id:payload.session_id,resume_token:payload.resume_token});await loadCurrent()}catch(e){setStatus('startStatus',e.message,true)}};
$('showRecovery').onclick=()=>{$('recovery').classList.remove('hidden');$('recoveryEmail').value=$('email').value};$('cancelRecovery').onclick=()=>$('recovery').classList.add('hidden');
$('requestCode').onclick=async()=>{try{await api('/api/life-patterns/interview/recovery/request',{method:'POST',body:JSON.stringify({email:$('recoveryEmail').value})});setStatus('recoveryStatus','If a matching interview exists and email recovery is configured, a one-time code has been sent.')}catch(e){setStatus('recoveryStatus',e.message,true)}};
$('verifyCode').onclick=async()=>{try{const payload=await api('/api/life-patterns/interview/recovery/verify',{method:'POST',body:JSON.stringify({email:$('recoveryEmail').value,otp:$('otp').value})});saveSession({session_id:payload.session_id,resume_token:payload.resume_token});await loadCurrent()}catch(e){setStatus('recoveryStatus',e.message,true)}};
$('send').onclick=async()=>{const text=$('message').value.trim();if(!text||!session)return;addBubble('user',text);$('message').value='';$('send').disabled=true;$('saveState').textContent='Saving…';try{const payload=await api(`/api/life-patterns/interview/sessions/${encodeURIComponent(session.session_id)}/turns`,{method:'POST',body:JSON.stringify({token:session.resume_token,message:text,input_modality:'typed'})});$('saveState').textContent='Saved';addBubble('ai',payload.reply);renderProgress(payload.progress);if(payload.provisional_insight){$('insight').textContent=payload.provisional_insight;$('insight').classList.remove('hidden')}setStatus('turnStatus',payload.episode_saved?'A concrete episode was added to your evidence map.':'Your turn was saved.') }catch(e){$('saveState').textContent='Your message was saved; AI reply failed';setStatus('turnStatus',e.message,true)}finally{$('send').disabled=false}};
$('message').addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter')$('send').click()});
$('pause').onclick=()=>{setStatus('turnStatus','Everything completed so far is saved. You can close this page and resume later on this device or by email OTP.');localStorage.setItem(storageKey,JSON.stringify(session))};
$('mapButton').onclick=async()=>{if(!session)return;$('mapButton').disabled=true;try{const payload=await api(`/api/life-patterns/interview/sessions/${encodeURIComponent(session.session_id)}/map`,{method:'POST',body:JSON.stringify({token:session.resume_token})});renderMap(payload.life_patterns_map)}catch(e){setStatus('turnStatus',e.message,true)}finally{$('mapButton').disabled=false}};
function renderMap(map){$('mapPanel').classList.remove('hidden');$('mapContent').textContent='';const summary=document.createElement('p');summary.textContent=map.overall_summary;$('mapContent').append(summary);for(const pattern of map.patterns||[]){const box=document.createElement('div');box.className='card soft';const title=document.createElement('strong');title.textContent=pattern.title;const p=document.createElement('p');p.textContent=pattern.summary;const small=document.createElement('p');small.className='note';small.textContent='Status: '+pattern.status+' · confidence '+Number(pattern.confidence).toFixed(2);box.append(title,p,small);$('mapContent').append(box)}$('mapPanel').scrollIntoView({behavior:'smooth'})}
$('exportButton').onclick=async()=>{if(!session)return;try{const payload=await api(`/api/life-patterns/interview/sessions/${encodeURIComponent(session.session_id)}/export?token=${encodeURIComponent(session.resume_token)}`);$('coachingContext').textContent=payload.coaching_markdown;$('exportPanel').classList.remove('hidden')}catch(e){setStatus('turnStatus',e.message,true)}};
const restored=localStorage.getItem(storageKey);if(restored){try{session=JSON.parse(restored);loadCurrent()}catch{localStorage.removeItem(storageKey)}}
</script>
</main></body></html>'''
