"""Neutral behavioral dimensions for the Life Patterns recoverability candidate."""

from __future__ import annotations

from .life_patterns_v2_owner_coverage import CoverageDomain

RECOVERABILITY_DOMAINS: tuple[CoverageDomain, ...] = (
    CoverageDomain("complex_structure", "Complexity, detail, and structure", "How complex material is decomposed, organized, classified, tested, or kept holistic.", "When you are trying to understand something genuinely complicated, what do you naturally do with the details—organize them into definitions or categories, keep a looser overall picture, test examples, or something else?"),
    CoverageDomain("insight_translation", "Insight and translation", "What happens after an insight forms: private knowing, explanation, demonstration, protocol, system, or other translation.", "When you finally understand something difficult, what tends to happen next—does it stay mostly intuitive or private, become a concise explanation, turn into a reusable system or protocol, or depend on the situation?"),
    CoverageDomain("recurring_mystery", "Unresolved questions and return", "Whether consequential unresolved questions recur, how they return, and what creates enough closure to stop returning.", "What tends to happen with an important question you cannot resolve—do you keep returning to it, put it down for long periods, revisit only when something prompts you, or something else? What makes it feel finished enough to stop?"),
    CoverageDomain("original_contribution", "Original contribution versus inherited method", "When established methods are adopted, modified, rejected, or replaced by a personally developed approach.", "When you work in an area that already has established methods, what makes you use them as they are versus modify them or develop your own way?"),
    CoverageDomain("persuasion_strategy", "Persuasion capacity and preferred use", "Ability to adapt framing or leverage to an audience, separated from whether the person prefers to use that ability.", "When you really need another person to understand or agree with something, how much do you adapt the framing to what will move them—and is that different from how you prefer to communicate when persuasion is not necessary?"),
    CoverageDomain("recognition_entry", "Entry, recognition, and role acceptance", "How social, romantic, communal, or work roles begin and what signals that stepping in is appropriate.", "In a new relationship, group, or role, how do you usually know when to step in—do you initiate, wait for a clear opening or recognition, respond to a request, or does it depend on the setting?"),
    CoverageDomain("network_pathways", "Networks and opportunity pathways", "How important opportunities, collaborators, customers, roles, or influence usually propagate through social versus impersonal channels.", "How do important opportunities or connections usually reach you—through people who already know you or your work, direct outreach, impersonal discovery, deliberate self-promotion, or some mixture?"),
    CoverageDomain("role_projection", "Role projection and misrecognition", "Whether other people assign capabilities, responsibilities, or identities beyond what the person claimed, and what follows when expectations diverge.", "Do people ever assign you a broader role or capability than you actually claimed? If so, what tends to happen when their expectation and what you can or want to provide diverge?"),
    CoverageDomain("immediate_body_signal", "Immediate bodily or felt signals", "Rapid bodily/felt information before extended reasoning, including clarity, repeatability, confidence, override, and state dependence.", "When an important choice or safety question comes up, do you ever get an immediate bodily or felt signal before you have reasoned it through? If so, how clear, repeatable, and trustworthy is it—and when is it easy to miss or override?"),
    CoverageDomain("autonomy_direction", "Autonomy, direction, and external roles", "What remains self-directed versus what changes under roles, institutions, relationships, or environmental pressure.", "When a role, institution, relationship, or environment pushes you in a direction, what tends to stay stable about your own direction or way of operating, and what is more likely to change?"),
    CoverageDomain("sanctuary_sensory", "Home, sensory baseline, and sanctuary", "Physical, sensory, environmental, privacy, and home-base conditions that materially alter functioning or restoration.", "What physical or sensory conditions in your home or surroundings make a large difference to how well you think, work, or recover, if any?"),
    CoverageDomain("romantic_attachment", "Romantic and attachment dynamics", "Attraction, closeness, reciprocity, sensuality, attachment, autonomy, and what deepens or weakens romantic connection.", "In romantic or sexual connection, what tends to create attraction for you, and what makes closeness deepen or fade? You can say you do not know or prefer not to answer."),
    CoverageDomain("emotion_permeability", "Emotional baseline and permeability", "Baseline affect alone, response to other people's emotional states, conflict amplification, and recovery after separation or decompression.", "What is your emotional baseline like when you are on your own, and what changes when you are around someone who is strongly emotional or in conflict? How quickly do you usually return to baseline afterward?"),
    CoverageDomain("work_energy_range", "Work energy across intensity and duration", "Energy under engaging work, ordinary workload, concentrated bursts, prolonged overload, stopping signals, and recovery.", "How does meaningful or engaging work affect your energy at ordinary workload versus an intense burst or a prolonged period of overwork, and how do you know when you genuinely need to stop?"),
    CoverageDomain("consequential_effort", "Consequential effort, struggle, and purpose", "What makes a problem worth sustained effort or risk, how purpose changes the form of effort, and what makes a previously important struggle no longer worth continuing.", "What makes a problem important enough that you will sustain serious effort or struggle for it, and what makes you disengage even after you have already invested a lot?"),
    CoverageDomain("correction_threshold", "Correction threshold", "What determines whether an error, falsehood, inefficiency, or broken rule is challenged versus ignored.", "When you believe something is wrong, what determines whether you correct or challenge it versus simply let it go?"),
    CoverageDomain("retreat_privacy", "Retreat, privacy, and re-entry", "Need for withdrawal after social intensity or major experience, what happens during retreat, and what permits re-entry.", "After intense social contact or a major life experience, what do you usually need before you want to re-engage with people or outward activity?"),
    CoverageDomain("value_tension", "Value tension and competing priorities", "How persistent conflict between important values, obligations, needs, or ideals is experienced and resolved.", "When two things that both matter to you pull in different directions, what do you tend to do—resolve it quickly, live with the tension, prioritize one, keep switching, or something else?"),
    CoverageDomain("resource_motivation", "Resources, status, security, and sovereignty", "What money, material control, status, ownership, and enterprise are for in practice: autonomy, comfort, security, achievement, influence, rank, or other motives.", "What do money, resources, ownership, or status mainly mean to you in practice—security, autonomy, comfort, achievement, influence, rank, something else, or different things in different contexts?"),
    CoverageDomain("developmental_phases", "Developmental phases and learned change", "Distinct life phases, childhood-to-adult continuity, learned management, and major changes in how recurring tendencies are expressed.", "Looking across your life, are there clear phases where the way you engage with problems, people, or the world changed substantially? Which tendencies feel continuous from childhood and which were learned or transformed?"),
    CoverageDomain("rhythm_continuity", "Rhythm, routine, and continuity", "Preference for routine versus novelty, self-directed scheduling, continuity, stable baselines, and conditions under which rhythm is disrupted.", "How important are stable routines or continuity in your daily life, and when do you prefer novelty or major change instead?"),
    CoverageDomain("focus_repetition", "Concentrated focus and repetition", "Depth and duration of focus, stillness, practice, repetition, mastery, and whether repetition is intrinsically rewarding or merely instrumental.", "When you become deeply focused on something, what keeps you there—and how do you relate to repetition or practice? Is repeating the activity satisfying in itself, useful only for a goal, or does it depend?"),
    CoverageDomain("needs_responsibility", "Sensitivity to needs and responsibility", "How readily other people's or a group's needs are noticed, what creates felt responsibility, and when care or intervention is deliberately withheld.", "When you notice that someone or a group needs support, how quickly do you notice it, and what determines whether you feel responsible to step in versus leave it alone?"),
)
