"""Confirmatory participant UI layered over the direct-OpenAI questionnaire UI."""

from __future__ import annotations

from hdmatch.api.relationship_openai_ui import HTML as BASE_HTML


def _replace_once(text: str, old: str, new: str) -> str:
    if old not in text:
        raise RuntimeError(f"expected study UI fragment not found: {old[:100]!r}")
    return text.replace(old, new, 1)


HTML = BASE_HTML
HTML = _replace_once(
    HTML,
    ".consent-line{display:block;margin:9px 0}\n</style>",
    ".consent-line{display:block;margin:9px 0}.birth-panel{border:1px solid #ddd;border-radius:10px;padding:14px;margin:14px 0}.birth-panel input,.birth-panel select{padding:7px;margin:4px 5px 8px 0;max-width:100%}.birth-panel input[type=text],.birth-panel input[type=email]{width:min(480px,100%);box-sizing:border-box}.birth-time-group{display:flex;align-items:center;gap:5px;margin:4px 0 2px}.birth-time-group label{display:flex;flex-direction:column;gap:2px}.birth-time-box{width:3.5rem!important;text-align:center}.birth-time-separator{font-size:1.4rem;margin-top:17px}.field-error{color:#a40000;font-weight:600;margin:2px 0 8px}.place-results button{display:block;text-align:left;width:100%;margin:6px 0;padding:8px}.study-status{padding:10px;margin:10px 0;background:#f6f6f6}.result-axis{border-top:1px solid #ddd;padding:10px 0}.technical{margin-top:16px;color:#555}\n</style>",
)
HTML = _replace_once(
    HTML,
    "<div id=\"start\" class=\"card\">\n"
    "<div id=\"llmStatus\" class=\"notice\">Checking AI auditor…</div>\n"
    "<label class=\"consent-line\"><input id=\"storageConsent\" type=\"checkbox\"> I consent to storing these responses privately for this research session.</label>\n"
    "<label class=\"consent-line\"><input id=\"llmConsent\" type=\"checkbox\"> I consent to these questionnaire answers being sent to OpenAI's API for answer-quality and clarification analysis. Birth/chart data and Astro/HD predictions are not sent to this auditor.</label>\n"
    "<button id=\"beginButton\" onclick=\"begin()\" disabled>Begin</button>\n"
    "</div>",
    "<div id=\"start\" class=\"card\">\n"
    "<h2>Start with the birth data</h2>\n"
    "<p>The astrology/Human Design prediction is calculated and cryptographically sealed <strong>before</strong> you answer anything about the relationship. The questionnaire AI never sees the birth data or hidden prediction.</p>\n"
    "<div id=\"llmStatus\" class=\"notice\">Checking AI auditor…</div>\n"
    "<label>Email for this study<br><input id=\"contactEmail\" type=\"email\" autocomplete=\"email\" placeholder=\"you@example.com\"></label>\n"
    "<p class=\"hint\">We store the email privately for future result/recovery delivery. Email verification is not connected yet, so for this pilot the private resume credential is still stored in this browser.</p>\n"
    "<div class=\"birth-panel\"><h3>You</h3>\n"
    "<label>Birth date <input id=\"aBirthDate\" type=\"date\"></label><br>\n"
    "<label><input id=\"aUnknownTime\" type=\"checkbox\" onchange=\"toggleUnknownTime('a')\"> Birth time unknown</label><br>\n"
    "<div class=\"birth-time-group\" role=\"group\" aria-label=\"Your birth time in 24-hour format\"><label>Hour (00–23)<input class=\"birth-time-box\" id=\"aBirthHour\" type=\"text\" inputmode=\"numeric\" pattern=\"[0-9]*\" maxlength=\"2\" autocomplete=\"off\" aria-describedby=\"aBirthTimeError\" oninput=\"clearBirthTimeError('a')\"></label><span class=\"birth-time-separator\">:</span><label>Minute (00–59)<input class=\"birth-time-box\" id=\"aBirthMinute\" type=\"text\" inputmode=\"numeric\" pattern=\"[0-9]*\" maxlength=\"2\" autocomplete=\"off\" aria-describedby=\"aBirthTimeError\" oninput=\"clearBirthTimeError('a')\"></label></div><p id=\"aBirthTimeError\" class=\"field-error hidden\" role=\"alert\" aria-live=\"polite\"></p>\n"
    "<label>Time source <select id=\"aTimeSource\"><option value=\"birth_certificate\">Birth certificate</option><option value=\"hospital_record\">Hospital record</option><option value=\"parent_or_family_memory\">Parent/family memory</option><option value=\"personal_memory\">Personal memory</option><option value=\"estimated\">Estimated</option></select></label><br>\n"
    "<label>Birthplace <input id=\"aPlaceQuery\" type=\"text\" placeholder=\"City, region, country\"></label><button type=\"button\" onclick=\"searchPlace('a')\">Search birthplace</button><div id=\"aPlaceChosen\" class=\"hint\"></div><div id=\"aPlaceResults\" class=\"place-results\"></div></div>\n"
    "<div class=\"birth-panel\"><h3>The other person</h3>\n"
    "<label>Birth date <input id=\"bBirthDate\" type=\"date\"></label><br>\n"
    "<label><input id=\"bUnknownTime\" type=\"checkbox\" onchange=\"toggleUnknownTime('b')\"> Birth time unknown</label><br>\n"
    "<div class=\"birth-time-group\" role=\"group\" aria-label=\"The other person's birth time in 24-hour format\"><label>Hour (00–23)<input class=\"birth-time-box\" id=\"bBirthHour\" type=\"text\" inputmode=\"numeric\" pattern=\"[0-9]*\" maxlength=\"2\" autocomplete=\"off\" aria-describedby=\"bBirthTimeError\" oninput=\"clearBirthTimeError('b')\"></label><span class=\"birth-time-separator\">:</span><label>Minute (00–59)<input class=\"birth-time-box\" id=\"bBirthMinute\" type=\"text\" inputmode=\"numeric\" pattern=\"[0-9]*\" maxlength=\"2\" autocomplete=\"off\" aria-describedby=\"bBirthTimeError\" oninput=\"clearBirthTimeError('b')\"></label></div><p id=\"bBirthTimeError\" class=\"field-error hidden\" role=\"alert\" aria-live=\"polite\"></p>\n"
    "<label>Time source <select id=\"bTimeSource\"><option value=\"birth_certificate\">Birth certificate</option><option value=\"hospital_record\">Hospital record</option><option value=\"parent_or_family_memory\">Parent/family memory</option><option value=\"personal_memory\">Personal memory</option><option value=\"estimated\">Estimated</option></select></label><br>\n"
    "<label>Birthplace <input id=\"bPlaceQuery\" type=\"text\" placeholder=\"City, region, country\"></label><button type=\"button\" onclick=\"searchPlace('b')\">Search birthplace</button><div id=\"bPlaceChosen\" class=\"hint\"></div><div id=\"bPlaceResults\" class=\"place-results\"></div></div>\n"
    "<p class=\"hint\">Birthplace search sends only the place text to OpenStreetMap Nominatim. Email, birth date/time, relationship answers, and hidden predictions are not sent to the geocoder. Choose the correct result rather than relying on an automatic guess.</p>\n"
    "<label class=\"consent-line\"><input id=\"storageConsent\" type=\"checkbox\"> I consent to storing my email, birth data, and relationship responses privately for this research session.</label>\n"
    "<label class=\"consent-line\"><input id=\"partnerConsent\" type=\"checkbox\"> I consent to this study processing the other person's birth data for the relationship calculation.</label>\n"
    "<label class=\"consent-line\"><input id=\"llmConsent\" type=\"checkbox\"> I consent to my questionnaire answers being sent to OpenAI's API for answer-quality and clarification analysis. Birth/chart data and Astro/HD predictions are not sent to this auditor.</label>\n"
    "<div id=\"studyStatus\" class=\"study-status hidden\"></div><button id=\"beginButton\" onclick=\"beginStudy()\" disabled>Seal prediction &amp; begin questionnaire</button>\n"
    "</div>",
)
HTML = _replace_once(
    HTML,
    "<div id=\"done\" class=\"card hidden\"><h2>Responses frozen</h2><p id=\"doneText\">Your answers are sealed.</p><p class=\"receipt\" id=\"digest\"></p><div id=\"addendumBox\" class=\"hidden\"><div class=\"notice\">This run was frozen before the LLM auditor reviewed it. The original receipt will remain unchanged.</div><label class=\"consent-line\"><input id=\"addendumConsent\" type=\"checkbox\"> I consent to sending this frozen survey's questionnaire answers to OpenAI's API for a separate LLM audit addendum.</label><button id=\"addendumButton\" onclick=\"startLLMAddendum()\">Run LLM audit addendum</button></div></div>",
    "<div id=\"done\" class=\"card hidden\"><h2>Responses frozen</h2><p id=\"doneText\">Your answers are sealed.</p><div id=\"studyResults\" class=\"hidden\"><h2>Your relationship fingerprint</h2><div id=\"fingerprint\"></div><button id=\"revealButton\" onclick=\"revealStudy()\">Reveal the blinded Astro/HD prediction</button><div id=\"predictionReveal\" class=\"hidden\"></div></div><details class=\"technical\"><summary>Technical audit receipt</summary><p>You do not need to save this hash. It is provenance showing exactly which frozen record was used.</p><p class=\"receipt\" id=\"digest\"></p></details><div id=\"addendumBox\" class=\"hidden\"><div class=\"notice\">This run was frozen before the LLM auditor reviewed it. The original receipt will remain unchanged.</div><label class=\"consent-line\"><input id=\"addendumConsent\" type=\"checkbox\"> I consent to sending this frozen survey's questionnaire answers to OpenAI's API for a separate LLM audit addendum.</label><button id=\"addendumButton\" onclick=\"startLLMAddendum()\">Run LLM audit addendum</button></div></div>",
)
HTML = _replace_once(
    HTML,
    "let llmConfigured=false;",
    "let llmConfigured=false;let isStudySession=false;let selectedPlaces={a:null,b:null};let placeCandidates={a:[],b:[]};",
)
_old_begin = "async function begin(){if(!document.getElementById('storageConsent').checked||!document.getElementById('llmConsent').checked)return alert('Both storage and LLM-processing consent are required.');const r=await fetch('/api/adaptive/sessions',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({consent_to_store_responses:true,consent_to_llm_processing:true})});const d=await r.json();if(!r.ok)return alert(d.detail||'Could not start');sessionId=d.session_id;token=d.resume_token;localStorage.setItem('rr_session',sessionId);localStorage.setItem('rr_token',token);setProgress(d.progress);showQuestion(d.next_question)}"
_new_begin = r"""function clearBirthTimeError(role){const error=document.getElementById(role+'BirthTimeError');error.textContent='';error.classList.add('hidden')}
function failBirthTime(role,message,suffix){const error=document.getElementById(role+'BirthTimeError');error.textContent=message;error.classList.remove('hidden');document.getElementById(role+suffix).focus();throw new Error(message)}
function readBirthTime(role){const who=role==='a'?'your':"the other person's";const hourText=document.getElementById(role+'BirthHour').value.trim();const minuteText=document.getElementById(role+'BirthMinute').value.trim();if(!hourText&&!minuteText)return failBirthTime(role,'Enter '+who+' birth hour and minute, or mark the time unknown.','BirthHour');if(!/^\d{1,2}$/.test(hourText))return failBirthTime(role,'Enter '+who+' birth hour as a number from 00 to 23.','BirthHour');if(!/^\d{1,2}$/.test(minuteText))return failBirthTime(role,'Enter '+who+' birth minute as a number from 00 to 59.','BirthMinute');const hour=Number(hourText);const minute=Number(minuteText);if(hour>23)return failBirthTime(role,'Enter '+who+' birth hour from 00 to 23.','BirthHour');if(minute>59)return failBirthTime(role,'Enter '+who+' birth minute from 00 to 59.','BirthMinute');clearBirthTimeError(role);return String(hour).padStart(2,'0')+':'+String(minute).padStart(2,'0')+':00'}
function toggleUnknownTime(role){const unknown=document.getElementById(role+'UnknownTime').checked;document.getElementById(role+'BirthHour').disabled=unknown;document.getElementById(role+'BirthMinute').disabled=unknown;document.getElementById(role+'TimeSource').disabled=unknown;clearBirthTimeError(role)}
async function searchPlace(role){const q=document.getElementById(role+'PlaceQuery').value.trim();if(q.length<2)return alert('Enter a city/place to search.');const box=document.getElementById(role+'PlaceResults');box.textContent='Searching…';try{const r=await fetch('/api/study/places?q='+encodeURIComponent(q));const d=await r.json();if(!r.ok){box.textContent=d.detail||'Birthplace search failed.';return}placeCandidates[role]=d.candidates||[];if(!placeCandidates[role].length){box.textContent='No matches. Add region/country and try again.';return}box.innerHTML=placeCandidates[role].map((p,i)=>'<button type="button" onclick="choosePlace(\''+role+'\','+i+')">'+esc(p.display_name)+' · '+esc(p.iana_timezone)+'</button>').join('')}catch(e){box.textContent='Birthplace search failed.'}}
function choosePlace(role,index){const p=placeCandidates[role][index];selectedPlaces[role]=p;document.getElementById(role+'PlaceChosen').textContent='Selected: '+p.display_name+' · '+p.iana_timezone;document.getElementById(role+'PlaceResults').innerHTML=''}
function requireBirthField(role,suffix,message){const field=document.getElementById(role+suffix);field.focus();throw new Error(message)}
function birthPayload(role){const who=role==='a'?'your':"the other person's";const date=document.getElementById(role+'BirthDate').value;const unknown=document.getElementById(role+'UnknownTime').checked;const place=selectedPlaces[role];if(!date)requireBirthField(role,'BirthDate','Enter '+who+' birth date.');const time=unknown?null:readBirthTime(role);if(!place)requireBirthField(role,'PlaceQuery','Search and select '+who+' birthplace.');return {birth_date:date,local_time:time,birthplace:place.display_name,iana_timezone:place.iana_timezone,time_source:unknown?'unknown':document.getElementById(role+'TimeSource').value,uncertainty_minutes:null,latitude:place.latitude,longitude:place.longitude}}
async function beginStudy(){if(!llmConfigured)return alert('AI auditor is not ready.');const email=document.getElementById('contactEmail').value.trim();if(!email)return alert('Enter your email.');if(!document.getElementById('storageConsent').checked||!document.getElementById('partnerConsent').checked||!document.getElementById('llmConsent').checked)return alert('All three study consents are required.');let a,b;try{a=birthPayload('a');b=birthPayload('b')}catch(e){return alert(e.message)}const button=document.getElementById('beginButton');button.disabled=true;button.textContent='Sealing hidden prediction…';const status=document.getElementById('studyStatus');status.classList.remove('hidden');status.textContent='Calculating and freezing the pre-answer Astro/HD record. No relationship answer has been submitted yet.';try{const r=await fetch('/api/study/intake',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({intake:{contact_email:email,respondent_birth:a,partner_birth:b,consent_to_store_private_research_data:true,consent_to_process_partner_birth_data:true,created_at_utc:new Date().toISOString()},consent_to_llm_processing:true})});const d=await r.json();if(!r.ok){status.textContent=d.detail||'Could not save study intake.';button.disabled=false;button.textContent='Seal prediction & begin questionnaire';return}sessionId=d.session_id;token=d.resume_token;isStudySession=true;localStorage.setItem('rr_session',sessionId);localStorage.setItem('rr_token',token);if(!d.preflight.confirmatory_ready){status.textContent=d.participant_message+' Prediction status: '+JSON.stringify(d.preflight.prediction_layer_statuses);button.textContent='Prediction not ready';return}const state=await loadState();coreProgress(state.answers.length);if(state.next_question)showQuestion(state.next_question);else startAudit()}catch(e){status.textContent='Could not initialize the study.';button.disabled=false;button.textContent='Seal prediction & begin questionnaire'}}"""
HTML = _replace_once(HTML, _old_begin, _new_begin)
_old_freeze = "async function freezeCurrent(){const r=await fetch('/api/adaptive/sessions/'+sessionId+'/freeze',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({token})});const d=await r.json();if(!r.ok)return alert(d.detail||'Could not freeze');showDone(d.freeze_sha256,false,false)}"
_new_freeze = r"""async function freezeCurrent(){const r=await fetch('/api/adaptive/sessions/'+sessionId+'/freeze',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({token})});const d=await r.json();if(!r.ok)return alert(d.detail||'Could not freeze');showDone(d.freeze_sha256,false,false);if(isStudySession)finishStudyAfterFreeze()}
async function finishStudyAfterFreeze(){document.getElementById('doneText').textContent='Your answers are sealed. Building the chart-blind relationship fingerprint…';const r=await fetch('/api/study/sessions/'+sessionId+'/phenotype-freeze',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({token})});const d=await r.json();if(!r.ok){document.getElementById('doneText').textContent=d.detail||'Phenotype classification failed; the answers remain safely frozen.';return}const f=await fetch('/api/study/sessions/'+sessionId+'/fingerprint?token='+encodeURIComponent(token));const fp=await f.json();if(!f.ok){document.getElementById('doneText').textContent=fp.detail||'Fingerprint is unavailable.';return}renderFingerprint(fp);document.getElementById('studyResults').classList.remove('hidden');document.getElementById('doneText').textContent='Your chart-blind relationship fingerprint is sealed. You can now reveal what the pre-answer Astro/HD system actually predicted.'}
function renderFingerprint(fp){const rows=(fp.classified_axes||[]).map(a=>'<div class="result-axis"><strong>'+esc(a.axis_id.replaceAll('_',' '))+'</strong> · '+esc(a.direction)+' · <strong>'+esc(a.value||a.status)+'</strong>'+(a.trajectory&&a.trajectory!=='unknown'?' · '+esc(a.trajectory):'')+'<div class="hint">'+esc(a.definition||'')+'</div></div>').join('');const unresolved=(fp.unresolved_or_mixed_axes||[]).length;document.getElementById('fingerprint').innerHTML=(rows||'<p>No axes met the frozen evidence/confidence threshold.</p>')+(unresolved?'<p class="hint">'+unresolved+' additional axes remain mixed, context-dependent, or insufficiently observed.</p>':'')}
async function revealStudy(){const b=document.getElementById('revealButton');b.disabled=true;b.textContent='Revealing frozen prediction…';const r=await fetch('/api/study/sessions/'+sessionId+'/reveal',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({token})});const d=await r.json();if(!r.ok){b.disabled=false;b.textContent='Reveal the blinded Astro/HD prediction';return alert(d.detail||'Reveal failed')}const target=document.getElementById('predictionReveal');target.classList.remove('hidden');target.innerHTML=renderPrediction(d.prediction_reveal);b.classList.add('hidden')}
function renderPrediction(p){let html='<h2>What was frozen before your answers</h2>';for(const layer of (p.layers||[])){html+='<div class="card"><h3>'+esc(layer.layer_id.replaceAll('_',' '))+'</h3><p>'+esc(layer.explanation||layer.outcome_comparison_status)+'</p>';if(layer.layer_id==='human_design_connection_v1'&&layer.preanswer_payload&&layer.preanswer_payload.connection){const c=layer.preanswer_payload.connection;html+='<p><strong>Connection mechanics:</strong> '+esc(c.center_configuration||'')+' · '+esc(c.composite_definition||'')+'</p>';if(c.channels)html+='<p class="hint">Channels: '+esc(c.channels.map(x=>x.channel+' ('+x.kind+')').join(', '))+'</p>'}if(layer.layer_id==='astro_rrf_directional_v0_4'&&layer.preanswer_payload&&layer.preanswer_payload.v0_1_raw_scoring){html+='<p><strong>Frozen directional raw signals:</strong></p><ul>'+layer.preanswer_payload.v0_1_raw_scoring.directional_scores.map(x=>'<li>'+esc(x.actor.toUpperCase()+' · '+x.axis.replaceAll('_',' ')+' = '+x.score)+'</li>').join('')+'</ul>'}html+='</div>'}if(!p.formal_hit_miss_summary)html+='<div class="notice"><strong>Why there is not a hit/miss percentage yet:</strong> the raw relationship signals were frozen before your answers, but the ordinal calibration needed to call those scores high/low is not yet frozen. The study will not invent that threshold after seeing your relationship.</div>';return html}"""
HTML = _replace_once(HTML, _old_freeze, _new_freeze)
_old_show_done = "function showDone(receipt,isAddendum,canAddendum){hideAll();document.getElementById('progressWrap').classList.add('hidden');document.getElementById('done').classList.remove('hidden');document.getElementById('doneText').textContent=isAddendum?'Your LLM audit addendum is frozen separately from the original response.':'Your answers are sealed.';document.getElementById('digest').textContent=(isAddendum?'LLM addendum freeze receipt: ':'Freeze receipt: ')+receipt;document.getElementById('addendumBox').classList.toggle('hidden',!canAddendum)}"
_new_show_done = "function showDone(receipt,isAddendum,canAddendum){hideAll();document.getElementById('progressWrap').classList.add('hidden');document.getElementById('done').classList.remove('hidden');document.getElementById('doneText').textContent=isAddendum?'Your LLM audit addendum is frozen separately from the original response.':'Your answers are sealed.';document.getElementById('digest').textContent=receipt;document.getElementById('addendumBox').classList.toggle('hidden',!canAddendum)}"
HTML = _replace_once(HTML, _old_show_done, _new_show_done)
_old_resume = "async function resume(){if(!(sessionId&&token))return;try{const d=await loadState();if(d.status==='frozen'){if(d.llm_addendum&&d.llm_addendum.status==='in_progress'){auditMode='addendum';setProgress(d.llm_addendum.progress);if(d.llm_addendum.next_clarification)showAuditQuestion(d.llm_addendum.next_clarification);else loadAddendumReview(d.llm_addendum);return}if(d.llm_addendum&&d.llm_addendum.status==='frozen'){showDone(d.llm_addendum.freeze_sha256,true,false);return}showDone(d.freeze_sha256,false,d.can_start_llm_addendum);return}coreProgress(d.answers.length);if(d.next_question)showQuestion(d.next_question);else if(d.semantic_audit&&d.semantic_audit.next_clarification){auditMode='core';setProgress(d.semantic_audit.progress);showAuditQuestion(d.semantic_audit.next_clarification)}else if(d.semantic_audit)loadReview(d.semantic_audit);else startAudit()}catch(e){}}"
_new_resume = r"""async function resume(){if(!(sessionId&&token))return;try{const pre=await fetch('/api/study/sessions/'+sessionId+'/preflight?token='+encodeURIComponent(token));if(pre.ok){isStudySession=true;const pf=await pre.json();if(!pf.confirmatory_ready){hideAll();document.getElementById('start').classList.remove('hidden');const s=document.getElementById('studyStatus');s.classList.remove('hidden');s.textContent='This study intake is saved, but the hidden prediction is not yet complete. No relationship questions are unlocked. Prediction status: '+JSON.stringify(pf.prediction_layer_statuses);return}}const d=await loadState();if(d.status==='frozen'){if(isStudySession){showDone(d.freeze_sha256,false,false);await finishStudyAfterFreeze();return}if(d.llm_addendum&&d.llm_addendum.status==='in_progress'){auditMode='addendum';setProgress(d.llm_addendum.progress);if(d.llm_addendum.next_clarification)showAuditQuestion(d.llm_addendum.next_clarification);else loadAddendumReview(d.llm_addendum);return}if(d.llm_addendum&&d.llm_addendum.status==='frozen'){showDone(d.llm_addendum.freeze_sha256,true,false);return}showDone(d.freeze_sha256,false,d.can_start_llm_addendum);return}coreProgress(d.answers.length);if(d.next_question)showQuestion(d.next_question);else if(d.semantic_audit&&d.semantic_audit.next_clarification){auditMode='core';setProgress(d.semantic_audit.progress);showAuditQuestion(d.semantic_audit.next_clarification)}else if(d.semantic_audit)loadReview(d.semantic_audit);else startAudit()}catch(e){}}"""
HTML = _replace_once(HTML, _old_resume, _new_resume)
