"""Verified, reusable exact-state century-cache contracts."""

from .models import (
    CacheableStateSource,
    CenturyCacheBuildSpec,
    CenturyCacheEngineProvenance,
    CenturyCacheExpectations,
    CenturyCacheManifest,
    CenturyCacheShard,
    CenturyStateRecord,
    FeatureColumnSpec,
    FeatureStorageType,
    FeatureValue,
    VerifiedCenturyCache,
    canonical_rows_sha256,
    coerce_century_state_record,
    feature_registry_sha256,
    parquet_schema_sha256,
    required_feature_ids_sha256,
)
from .parquet import CenturyCacheDependencyError, CenturyCacheParquetError
from .store import (
    CenturyCacheBuildError,
    CenturyCacheRecoveryError,
    CenturyCacheShardInput,
    CenturyCacheVerificationError,
    iter_verified_century_cache_rows,
    open_century_cache_for_recovery,
    verify_century_cache,
    write_century_cache_explicit,
)

__all__ = [
    "CacheableStateSource",
    "CenturyCacheBuildError",
    "CenturyCacheBuildSpec",
    "CenturyCacheDependencyError",
    "CenturyCacheEngineProvenance",
    "CenturyCacheExpectations",
    "CenturyCacheManifest",
    "CenturyCacheParquetError",
    "CenturyCacheRecoveryError",
    "CenturyCacheShard",
    "CenturyCacheShardInput",
    "CenturyCacheVerificationError",
    "CenturyStateRecord",
    "FeatureColumnSpec",
    "FeatureStorageType",
    "FeatureValue",
    "VerifiedCenturyCache",
    "canonical_rows_sha256",
    "coerce_century_state_record",
    "feature_registry_sha256",
    "iter_verified_century_cache_rows",
    "open_century_cache_for_recovery",
    "parquet_schema_sha256",
    "required_feature_ids_sha256",
    "verify_century_cache",
    "write_century_cache_explicit",
]
