"""Authored adversarial examples, not model executions or human observations."""
from pathlib import Path
import json
P=Path(__file__).resolve().parent
bank=json.loads((P/'interviewer-bank-v5.json').read_text()); Q={q['id']:q for q in bank['questions']}
C=[]
def case(name,qid,answer,next_id,next_text,keep,reject,review,history=''):
 C.append({'id':f'C{len(C)+1:02d}','name':name,'question_id':qid,'question':Q[qid]['question'],'prior_context':history,'fictional_answer':answer,'next_question_id':next_id,'reviewed_next_utterance':Q[next_id]['question'] if next_id in Q and next_text is None else next_text,'supported_record':keep,'rejected_continuation':reject,'semantic_review':review,'provenance':'same-context authored challenge and manual review; not a live respondent or independent classifier result'})
case('Bare agreement','A0',"Yes, I'd go.",'WHY',None,'Would accept in this scene; motive unknown.','You feel responsible for keeping your friend happy.','Open reason is warranted; neither guilt nor desire has been supplied.')
case('Reason already given','A0',"Yes, because I enjoy their company. I could read another time.",'G21',None,'Anticipated acceptance from enjoyment, with flexible personal plan.','Would you feel guilty about not going?','Move to a different topic; do not search for obligation behind the stated reason.')
case('Negotiated answer, not binary yes','A0',"I'd ask them to come over and read beside me.",None,'What would make that arrangement work for you?','Proposes shared quiet activity; reason remains unspecified.','What would make you say yes to going out?','Match the actual action; the respondent did not agree to go out.')
case('Ambiguous feeling','A0',"I'd go because otherwise I'd feel bad.",None,'What does “feel bad” mean for you here?','Anticipated acceptance and an unresolved feeling phrase.','So you feel guilty for being selfish.','Clarify the respondent’s phrase without importing a moral or emotional label.')
case('Already conditional','A0',"If they were lonely I'd go. If they just fancied company, I'd suggest tomorrow.",'G21',None,'Two explicit branches by perceived need; no universal yes/no.','But which response is the real you?','Keep both branches. Do not turn conditionality into contradiction or repeat the conditions question.')
case('No help antecedent','G23',"The food, probably.",'G01',None,'Attention to food; helping and responsibility unreported.','What would make you leave that help to someone else?','CARE-LIMIT and CARE-RESPONSIBILITY are ineligible without a specified need or helping choice.')
case('Specific helping, motive unclear','G23',"I'd notice someone doing all the washing up and go over to help.",None,'What would lead you to help in that situation?','Notices uneven work and anticipates helping; motive not yet specified.','You automatically take responsibility for everybody.','First clarify the stated action. A separate obligation probe is only useful if still material afterwards.')
case('Motive and boundary already supplied','CARE-RESPONSIBILITY',"Only my agreed part. If somebody else had offered to wash up, I would leave it to them.",'G01',None,'Limited responsibility plus explicit nonintervention condition.','What would make you leave that help to someone else?','CARE-LIMIT is already answered; a new ID cannot justify re-asking it.','A shared-meal need and the form of help were already named.')
case('No bodily reaction','G09',"Nothing physical that I notice. I'd just compare the times and what they teach.",'G10',None,'No noticed early bodily reaction; a reasoning procedure.','How useful is that bodily reaction?','Suppress R04, M10, SIGNAL-DEPENDABILITY and SIGNAL-NOT-FOLLOWED. Do not invent no sensation in every part of life.','Cooking-class E0 was presented and remains the active choice.')
case('Rich signal answer','G09',"Sometimes a brief tightness. It doesn't repeat during one decision, and I don't trust it when I'm exhausted.",'R04','Outside those exhausted periods, how useful is that reaction when you decide?','Intermittent bodily reaction; within-choice brevity; stated exhaustion limitation. Usefulness outside exhaustion is unresolved.','What usually happens to that reaction as you keep considering the choice?','Duration and the exhaustion condition are already given. The selected follow-up isolates only usefulness outside that condition; do not repeat either answered part.','Same cooking-class decision; no switch to a new commitment.')
case('Unknown is not absent','G09',"I don't know. I haven't paid attention to that.",'G10',None,'Uncertainty about a bodily response, not a report of no response.','Then you do not receive body signals.','Preserve unknown; move on without repetitions or positive/negative evidence.','Cooking-class scene is active.')
case('Decision already made','E0',"I'd sign up straight away; I could drop it later if it wasn't useful.",'G10',None,'Prompt commitment under reversibility; no ongoing deliberation reported.','As you keep considering that choice, how does clarity change?','Do not impose continued uncertainty; a body question is not compulsory merely because it remains open.')
case('Delayed follow-up has exact referent','MOOD-AFTER',"It tends to last until I stop replaying what was said.",'G21',None,'Aftermath of the earlier tense argument, not the later resources discussion.','How does your feeling about spending money settle?','The delivered wording must name the argument when nonadjacent. The actual question now names the earlier argument; a source note alone would not be enough.','R06: respondent reported tension during the accusation. Then G20 was discussed. Next utterance must be: After the argument you described earlier, what usually happens to that tension?')
case('No retreat need','G18',"I'd probably meet another friend. I don't usually need time alone afterwards.",'G21',None,'Anticipated further company and explicit lack of usual solitude need after that day.','What signals that you are ready to re-enter after retreat?','R11 is ineligible; social intensity in the stimulus does not establish withdrawal.')
case('Romance declined','G12',"I'd rather not discuss romantic relationships.",'G14',None,'Romance declined; no claim about attraction or attachment.','What about physical affection with a friend instead?','Respect the closed topic. Alone-time mood can be approached without routing around the refusal.')
case('Inapplicable partner, not all relationships','B0',"I don't have a partner; I'd be able to answer about a close friend.",None,'Using a close friend instead: they keep worrying about an upcoming gathering and are not asking you to do anything. What, if anything, would happen to your own mood?','User-elects friend context; keep romance unavailable and record the changed role.','Mark this as romantic emotional permeability.','A role substitution is permitted by the answer and explicitly recorded; it is not a psychometrically equivalent partner answer.')
case('Cancelled plans are not novelty resistance','C0',"I'd be disappointed because I wanted to see them, but glad to have the afternoon free.",'G21',None,'Mixed reaction: missing the friend and welcoming free time.','You find disruptions to routine difficult.','Keep the actual reasons; use ROUTINE-CHANGE only if novelty choice still matters.')
case('Invitation contrast retains task','R02',"I'd coordinate the food but let someone else handle the rest.",'G07',None,'Accepts bounded coordination when asked, compared with the original small-task response.','An invitation is required for you to act at all.','Compare actual scoped branches; no global rule or causal mechanism.','G06 answer: I would start chopping vegetables without waiting.')
case('Retrospective change without improvement assumption','G24',"Earlier I would go even when I didn't want to. Now I'd often offer another time.",'R12',None,'Reported earlier/current difference in the friend scene.','What healed you so that you can now set boundaries?','Ask attributed contributors without asserting pathology, improvement, treatment or a true original self.','Current A0 answer is known; retrospective comparison is welcome.')
case('Plain correction','A0',"Actually, I meant I'd suggest tomorrow, not go now.",'WHY','What would make you suggest tomorrow?','Append correction; supersede immediate acceptance and dependent interpretations only. The corrected action has no stated reason yet.','You are inconsistent about your social priorities.','Explicit correction is not a contradictory trait. Do not seek approval of the corrected paraphrase.')
case('Answer plus stop','A0',"Probably yes, but let's stop for now.",None,'We’ll stop here.','Save anticipated acceptance with motive unknown, plus pause; no follow-up.','What would make you say yes?','Stopping wins over the otherwise useful WHY question. Save status must be reported only after actual write verification.')
case('Norm and personal response in one message','A0',"People ought to make time for friends, but I'd probably stay home because I wanted to read.",'G21',None,'Normative view separate from anticipated personal refusal and reason.','You always prioritise friends because you believe people should.','Classify clauses separately; do not make the whole message normative or behavioral.')
case('Repeated confusion does not complete the profile','G17',"I still can't tell what kind of mistake you're talking about.",'G21',None,'Question remains unclear after repair; no correction-threshold evidence.','We have enough information to finish your profile.','Leave this scene aside and move to a different concrete task; do not call confusion success or silently end the interview.','One clarification of the meal time mistake was already given.')
case('Promise does not imply continued effort','M03',"I'd probably put it off, and tell them I might not finish.",None,'What would make you put it off?','Anticipates postponement and communication; motive unresolved.','What keeps you following through on every promise?','The revised action task admits not continuing; WHY must match the actual action.')
case('Deliberate counterfactual preserves earlier no','R10',"If I had joined, I'd stay only while there was a useful next step.",'G21',None,'Conditional hypothetical persistence after a clearly stipulated participation.','You spent a month restoring the space.','A knowingly imagined contrast is allowed; never back-fill an actual decision or event.','G16 answer was no. R10 explicitly introduced a different imagined participation premise.')
case('Stable signal absence does not close generic clarity','CHOICE-TIME',"Even with no body sensation, I usually become clearer once I understand the timetable.",'G10',None,'Clarity through information without a reported bodily signal.','No bodily signal means there is no decision process to ask about.','General clarity is independent of signal-specific follow-ups.','E0 decision is still under consideration; G09 reported no sensation.')
case('Context added by respondent','OWNERSHIP',"If there were restrictions on lending it to others, I'd want my own.",'G21',None,'Ownership motive conditional on a respondent-added access restriction.','You need ownership for status.','Store the condition and its origin; it is neither supplied fact nor a status motive.')
case('Pressure without action change','M01',"I'd feel rushed but keep doing it at the same pace.",'M02',None,'Internal urgency without reported speed change.','You speed up whenever someone pressures you.','Aftermath can be asked in the same task; action and internal reaction remain distinct.')
case('Affection is not desire','PHYSICAL-CLOSENESS',"I like cuddling, but I'd rather not talk about sex.",'G14',None,'Affection preference recorded; sexual topic declined.','Your sexual desire is high.','Keep private scope; do not substitute affection for desire or ask another sexual probe.')
case('Uncertainty plus usable condition','G21',"I'm not sure overall; when I'm rested I like leaving the day open.",'G11',None,'Qualified preference under rest; general rhythm unknown.','No usable information because the answer began I am not sure.','Preserve the explicit condition without promoting it to an overall preference.')
case('No identified skill','M07',"Nothing comes to mind.",'G01',None,'No named activity; skill history unassessed.','What do people ask you to do because of that ability?','M08 is ineligible. Do not transform retrieval difficulty into absence of talent.')
case('Refusal with enough information','G25',"I'd rely on them less for tasks, and I don't want to talk about repairing it.",'G21',None,'Task reliability reduced; repair topic closed.','What could make you trust them again?','Retain the answered part and respect refusal of the rest; do not erase trust evidence or reopen repair.')
C[12]['source_template']=C[12]['question']
C[12]['question']='After the argument you described earlier, what usually happens to that tension?'
C[12]['adaptation']='Restated the exact antecedent after a topic switch; no scene conditions changed.'
for item in C:
 if item['next_question_id'] in Q and item['reviewed_next_utterance'] != Q[item['next_question_id']]['question']:
  item['next_question_adaptation']='Bounded to the actual stated action or condition; literal delivered wording preserved.'
(P/'DIALOGUE-CHALLENGES.json').write_text(json.dumps(C,ensure_ascii=False,indent=2)+'\n')
lines=['# Adversarial dialogue review','', 'All examples below are newly authored design challenges reviewed in the same Chat context. They are not independent respondents, model runs, or estimates of error rates. Each next utterance was inspected for entailment, relevance, single-task burden and context. No example is an owner answer.','']
for c in C:
 lines += ['## '+c['id']+' — '+c['name'],'', 'Question: '+c['question']]
 if c['prior_context']:lines += ['','Earlier context: '+c['prior_context']]
 lines += ['', 'Fictional reply: '+c['fictional_answer'],'', 'Next utterance: '+str(c['reviewed_next_utterance']),'','Keep: '+c['supported_record'],'','Reject: '+c['rejected_continuation'],'','Review: '+c['semantic_review'],'']
(P/'DIALOGUE-CHALLENGES.md').write_text('\n'.join(lines)+'\n')
print('Authored and reviewed dialogue branches:',len(C))
