from pathlib import Path
import json, hashlib

ROOT = Path('/workspace/scratch/43f75264c32e/b02k-workers/source-b')
assert (ROOT/'SOURCE_FIRST_FREEZE.json').exists()
frozen = json.loads((ROOT/'SOURCE_FIRST_FREEZE.json').read_text())
assert hashlib.sha256((ROOT/'SOURCE_FIRST_NOTES.md').read_bytes()).hexdigest() == frozen['source_notes']['sha256']
rules=[]
aliases={}
section='Signes of a long or short Sicknesse (continuation)'
def add(key,pages,anchor,kind,conditions,assertion,exceptions=None,uncertainty=None,dependencies=None,logic=None,attribution='Lilly, Chapter XLIV'):
    rid=f'B{len(rules)+1:03d}'
    aliases[key]=rid
    if isinstance(pages,int): pages=[pages]
    rules.append(dict(id=rid,chapter='XLIV',section=section,pdf_pages=pages,printed_pages=[p-34 for p in pages],visible_printed_labels=[str(p-34) for p in pages],anchor=anchor,kind=kind,conditions=conditions,condition_logic={'status':'unresolved_source_grouping' if logic else 'preserved_source_prose','expression':logic or ' AND '.join(f'C{i+1}' for i in range(len(conditions))),'executable':False},assertion=assertion,exceptions=exceptions or [],uncertainty=uncertainty or [],scope='historical horary source only',dependencies=dependencies or [],attribution=attribution))

add('moon_ill_l1',283,'the Disease encreases','progression',['Moon applies to the lord of the ascendant by an ill aspect.'],'Lilly states that the disease increases.',uncertainty=['Ill aspect is not assigned a numerical threshold in this passage.'])
add('venus_self_blame',283,'the sick may thank himselfe','historical_attribution',['Moon is in the sixth house.','Moon is in ill aspect with Venus.'],'The source says the sick person may thank himself for the disease and calls him disorderly and of ill diet.',uncertainty=['This moralizing historical attribution is not clinical evidence or an assessment of a real person.'])
add('venus_scorpio',283,'he hath got a clap','historical_attribution',['The preceding Moon-in-sixth / ill-Venus-aspect context is in force.','Venus is in Scorpio, followed in print by etc.'],'The source attributes a clap to contact with an unclean woman.',uncertainty=['The scope of the preceding condition and the unexpanded etc. is not fully specified.','Historical sexual and moral allegation only; no modern diagnosis or validation.'],dependencies=['venus_self_blame'],logic='Preceding Moon/Venus condition; additional IF Venus in Scorpio, etc.; exact scope of etc. unresolved.')
add('venus_woman',283,'if a woman ask','historical_attribution',['The Moon/Venus passage is the immediate context.','A woman asks the question.'],'The source gives alternatives: too great a flux of Whites or Reds, or disease occasioned by her own folly, etc.',uncertainty=['It is unresolved whether the Scorpio condition is carried into this branch.','The historical terms and moral attribution are retained without clinical modernization.'],dependencies=['venus_self_blame','venus_scorpio'],logic='Female-question branch of preceding passage; scope of the additional Venus-in-Scorpio condition unresolved.')
add('l6_applies_l1',283,'is not yet at his height','progression',['The sixth lord applies to the ascendant lord by square OR opposition.'],'Lilly says the disease is increasing and has not reached its height or full growth.')
add('l6_eight_twelve',283,'great presumption','progression',['The sixth lord is in the eighth OR twelfth house.'],'Lilly calls this an ill argument and great presumption that the sick party must be more afflicted before the disease leaves him.')
add('malefic_exit',283,'the Disease will speedily alter','change',['An unfortunate planet is in the sixth house.','That planet is removing out of one sign into another.'],'Lilly says the disease will speedily alter.',uncertainty=['Alteration is not specified here as improvement or worsening.'])
add('exit_timing',283,'so many Moneth, Weeks or Dayes','timing_method',['The preceding sixth-house unfortunate-planet sign-exit configuration applies.','The question asks when or how long before the disease alters.'],'Lilly directs counting how many degrees the malevolent planet lacks before leaving the sign, then judging that many months, weeks, or days according to the sign’s nature and quality.',uncertainty=['No determinate month/week/day selection rule is supplied in this passage.','No rounding or partial-degree rule is supplied.'],dependencies=['malefic_exit'])
add('l6_complex_worsening',283,'from better to worse','progression_or_death',['The sixth lord is described as retrograde and combust.','He is in the eighth OR twelfth.','He is in square, opposition, OR conjunction with Saturn, Mars, the eighth lord, OR fourth lord.'],'The source says he prenotes much infirmity and a long continued and sudden alteration from better to worse, if not death itself.',uncertainty=['The wording combines long continued and sudden without resolving their relation.','Punctuation leaves the exact grouping of retrograde, combustion, placement, and aspect clauses uncertain.'],logic='Source sequence: Retrograde, Combust in eighth or twelfth, and in square/opposition/conjunction with Saturn/Mars/L8/L4; no definitive executable Boolean parse admitted.')
add('six_eight_swap',283,'Nature is not yet so overcome','source_tension',['The sixth lord is in the eighth.','The eighth lord is in the sixth.','A sextile OR trine exists between both significators.'],'The source prints “you shall not doubt of the death of the Patient at that time,” then explains that Nature is not yet so overcome or weak but that the sick shall overcome it. Both the wording and its survival-oriented explanation are retained.',uncertainty=['The historical meaning of doubt or a possible textual inconsistency is unresolved; do not silently substitute fear, life, or no death.'])
add('jupiter_medicines',283,'the sick felt great comfort','historical_treatment_attribution',['A trine, sextile, OR conjunction occurs between the sixth lord and Jupiter.','Jupiter is in the ninth house.','Moon separates from the sixth lord to Jupiter so placed in the ninth.'],'Lilly calls this an assured argument that medicines prescribed or already taken made the patient very sick while being taken and operating, wrought effectually in outward bodily parts, and afterward brought great comfort and improvement in the parts first afflicted.',uncertainty=['Historical inferential treatment narrative, not a verified clinical example.','The wording does not specify that every kind of discomfort implies effectiveness.'])
add('male6_danger',[283,284],'great danger in the Sicknesse','danger',['Saturn, Mars, OR any unfortunate planet is in the sixth.'],'The source says this threatens great danger in the sickness.',exceptions=['The next clause qualifies the threat if that planet is well affected or essentially fortified.'])
add('male6_fortified',284,'he hurts little','qualification',['A sixth-house unfortunate planet from the preceding rule is well affected OR essentially fortified.'],'The source says he hurts little; one may rather judge the disease happened casually and suddenly than from prepared bodily matter, and let the sick be of good comfort.',uncertainty=['Well affected and essentially fortified are not quantified here.','The bodily-cause claim remains a historical attribution.'],dependencies=['male6_danger'])
add('bene6_not_author',284,'will be permanent','duration',['A benevolent planet is well fortified in the sixth.','He is not the author of the disease.'],'Lilly says one may safely judge that the disease is not, or will not be, permanent.',uncertainty=['The source does not define an interval for permanent here.'])
add('witch_suspicion',284,'by an evill Spirit','historical_attribution',['A querent mistrusts witchcraft, in the stated context of some country towns.','The twelfth lord is in the sixth.'],'The source calls it a strong argument that the suspicion is true and that the party is vexed by an evil spirit or fascination.',uncertainty=['Source-defined supernatural attribution only, not evidence that witchcraft or spirits caused illness.'])
add('one_six_swap',284,'hath been of long continuance','duration',['The sixth lord is in the ascendant.','The ascendant lord is in the sixth.'],'Lilly says one may judge the disease has been long and will continue until one significator leaves its current sign.')
add('one_six_exit_death',284,'will then depart this Life','death_testimony',['The preceding exchange of first and sixth lords is in force.','At the significator’s transit to another sign he meets square/opposition of the fourth OR eighth lord, OR an oppressive/malicious Saturn OR Mars aspect.','The source adds that they are slow in motion and in signs odiously beholding/aspecting one another.'],'Lilly calls this a very great sign that the sick will die then.',uncertainty=['Plural pronouns and the range of the slow-motion/sign relationship conditions are unresolved.'],dependencies=['one_six_swap'],logic='Base exchange; at sign transit an adverse listed encounter; additional plural “they” slow-motion and hostile-sign conditions retained without resolving referents.')
add('azimene',284,'the Disease is uncurable','disease_quality',['The sixth lord is afflicted by square OR opposition of the ascendant lord in Azimene degrees.'],'The source dismisses the physician’s help and states that the disease is incurable and the sick continually pained.',uncertainty=['Whether in Azimene degrees modifies only the ascendant lord or the configuration is not explicit.','Azimene degrees are not enumerated in this passage.'],logic='L6 afflicted by square/opposition of L1 “in Azimen degrees”; attachment of the degree phrase unresolved.')
add('l6_asc_pain',284,'the paine doth slacken','duration',['The sixth lord is in the ascendant.'],'The disease continues, but pain slackens, seems removed at times, or the patient is sometimes not sensible of it.')
add('l6_cadent',284,'neither very grievous','duration',['The sixth lord is in a cadent house.'],'The source says the disease is neither very grievous nor will endure a long time.',uncertainty=['Long time is unquantified here.'])
add('good6_end',284,'good end of the Disease','recovery',['Good planets are in the sixth.'],'They promise a good end of the disease.')
add('evil6_end',284,'evill the contrary','adverse_outcome',['Evil planets are in the sixth.'],'The source gives the contrary of the good end promised by good planets.',uncertainty=['The contrary is not further specified as certain death in this clause.'],dependencies=['good6_end'])
add('male6_unsettled',284,'usually a malignant Planet','disease_quality',['A malignant planet is in the sixth.'],'Usually this shows the disease unsettled.',uncertainty=['Unsettled is not given a formal clinical or temporal definition.'])
add('l6_bad_places',284,'not easily curable','recovery_difficulty',['The sixth lord is in the sixth, eighth, OR twelfth.'],'This denotes a disease not easily curable.')
add('unafflicted_recovery',[284,285],'a faire signification of health','recovery',['The ascendant lord and Moon are free from square, opposition, OR conjunction of Saturn, Mars, OR any unfortunate planet.','They are described as direct, free of combustion, and swift in motion.','The list excludes peregrination, fall, detriment, being in eighth or sixth, and any aspect with the twelfth, sixth, or eighth lord.'],'The source calls this a fair signification of health and recovery.',uncertainty=['A long sentence changes from plural subject to singular possessives; exact application to both significators is not mechanically settled.','Negative scope over the final list is preserved; no thresholds are imported.'],logic='Source list of freedom from adverse aspects, direct/swift/noncombust condition, and negatives, with singular/plural attachment unresolved.')
add('l1_four_eight_good',285,'but recovery','recovery',['The ascendant lord is in the fourth OR eighth.','He is not afflicted.'],'The source says he signifies recovery, not death.')
add('l1_four_bad',285,'great difficulty','recovery_difficulty',['The ascendant lord is unfortunate in the fourth.'],'This notes great difficulty before the party is cured.',dependencies=['l1_four_eight_good'])
add('l1_bad_relapse',285,'possible he may be cured','recovery_then_relapse',['The ascendant lord is himself unfortunate: in his house, OR by retrogradation, peregrination, combustion, fall, OR detriment.'],'Cure is possible, but within a short time the source says the party will relapse, die, or fall into a desperate infirmity.',uncertainty=['The phrase either in his house does not unambiguously identify which kind of house-based misfortune is intended.','Short time is unquantified; the three subsequent outcomes remain alternatives.'])
add('l1_bad_l6_l12',285,'danger in the Disease threatened','danger',['The ascendant lord is infortunated by the sixth OR twelfth lord.','He is in a bad aspect of Moon.'],'Danger in the disease is threatened.')
add('saturn_l1_slow',285,'will be long sick','duration',['Saturn is lord of the ascendant.','He is in his dignities, slow, diminished in light, and retrograde.'],'The source especially cautions that the patient or querent will be long sick.',exceptions=['Judge the contrary of Saturn’s signification when otherwise qualified.'],uncertainty=['Otherwise qualified does not specify the exact contrasting subset; dignity is retained alongside the adverse conditions.'])
add('l1_angle_safe',285,'in no danger at this time','present_safety',['The ascendant lord is angular.','He has no configuration to a malevolent planet.','He is in a benevolent house of heaven.','He is neither under Sun’s beams nor retrograde.'],'One may judge the querent in no danger at this time.',uncertainty=['Benevolent house of heaven is not enumerated in this clause.'])
add('l1_sign_change',285,'the Disease will quickly determine','duration',['The ascendant lord is swift in motion.','He enters another sign OR goes out of his own house into another.','The destination is not the sign of the sixth OR twelfth.'],'The disease will quickly determine.',uncertainty=['Own house and another house are not silently converted into one exclusive technical sense.','Quickly has no fixed interval.'])
add('l1_nature_strong',285,'able to overcome the malignity','recovery',['The ascendant lord is not afflicted in himself or by an ill aspect of malevolents or planets contrary to his nature.','He is swift in motion.','He has a good aspect with fortunate planets.'],'Lilly calls this a strong argument that the diseased person’s nature is undiminished and able to overcome the disease’s malignity in a very short time.')
add('powerful_affliction',285,'a strong fit of sicknesse','severity',['The sick person’s significator is powerfully afflicted.'],'This is a sign of a strong fit of sickness; it is greater when the life significator is weaker than the afflicting planet.',uncertainty=['No numerical power or comparative-strength threshold is provided.'])
add('fixed_all',285,'a great space of time','duration',['All significators of the disease are in fixed signs.'],'This prenotes a great time before cure, which will not be easily perfected.')
add('male_applies_l1',285,'it retards the cure','duration',['A malevolent planet applies to the ascendant lord.'],'It retards cure and prolongs infirmity, though great hopes presently appear.')
add('slow_moon',[285,286],'lesse then her meane motion','duration',['Moon is slow, moving in twenty-four hours less than her mean motion.','Moon is in any aspect OR conjunction with the ascendant lord.'],'Moon likewise retards cure and prolongs infirmity under this carryover from the preceding malevolent-application statement.',uncertainty=['The source supplies twenty-four hours and comparison to mean motion, but no numerical mean-motion value.'],dependencies=['male_applies_l1'])
add('swift_moon',286,'effected in a little time','recovery',['The preceding Moon/ascendant-lord context is in force.','Moon is swift.'],'The source says the cure is performed presently or effected in a little time.',dependencies=['slow_moon'],uncertainty=['The text does not restate whether every preceding aspect condition continues into the but-if branch.'])
add('waning_saturn',286,'very mortall and dangerous','danger',['Moon decreases in light and motion.','Moon comes to conjunction, square, OR opposition of Saturn.'],'For the most part Lilly calls this very mortal and dangerous.',exceptions=['Unless the disease is in its decrease and leaving the patient or querent.'])
add('moon_oriental',286,'expect a short sicknesse','duration',['Moon is conjunct a planet that is oriental, direct, and swift.'],'Expect a short sickness.')
add('moon_retro_occ',286,'look for the contrary','duration',['Moon is joined to a retrograde OR occidental planet.'],'Look for the contrary of the preceding short-sickness judgment.',dependencies=['moon_oriental'])
add('scorpio_blame',286,'cause of his owne infirmnesse','historical_attribution',['Scorpio ascends.'],'For the most part the source judges the party to have caused his own infirmity by peevishness, folly, choler, or the like; the judgment is firmer if Mars is also in Scorpio.',uncertainty=['Historical moralizing cause attribution; no clinical or individual-person inference is made.'])
add('luminaries_cadent',286,'a terrible sicknesse','severity',['Both luminaries are in cadent houses.','Their dispositor or dispositors are unfortunate.'],'The querent may expect a terrible sickness.',exceptions=['The next Fortune-assistance branch changes the outcome while preserving long sickness.'])
add('fortunes_assist',286,'beyond all expectation','recovery_after_duration',['The preceding cadent-luminaries/unfortunate-dispositors configuration applies.','The Fortunes assist in judgment.'],'The sickness remains long and a sharp disease becomes chronic, yet beyond expectation the sick party recovers. The source advises more confidence as the Fortunes are more strongly dignified than the Infortunes.',uncertainty=['Comparative dignity has no numeric threshold in this paragraph.'],dependencies=['luminaries_cadent'])
add('mars_l1_venus',286,'no great danger','safety',['Mars is lord of the ascendant and in the sixth.','He is sextile OR trine Venus, or even square OR opposition of her.'],'There is no great danger.',uncertainty=['Conjunction is not listed in this particular sentence; it is not silently added.'])
add('l6_death_doubt',286,'you may doubt, and not unjustly','death_possibility',['The sixth lord is combust OR retrograde.','He is in his fall OR detriment and in the eighth.','He is conjunct, square, OR opposite Saturn OR Mars.'],'One may doubt, and not unjustly, that the disease will never leave the sick party until death.',uncertainty=['Source presents a warranted doubt or fear, not an unconditional certain-death statement.'])
add('moon_confirms_l6',286,'will be very certaine','corroboration',['The preceding sixth-lord configuration applies.','Moon has equal testimony, explicitly applying square, opposition, OR conjunction of the eighth lord.'],'The former judgment will be very certain.',dependencies=['l6_death_doubt'])
add('retro_bene_recovery',286,'the sick will recover','recovery_after_duration',['Moon OR ascendant lord is square, conjunct, OR opposite a benevolent planet.','The text immediately adds Retrograde.'],'The sick will recover but not in haste; this argues prolonged disease and relapsing from one disease into another.',uncertainty=['Retrograde appears to modify the benevolent planet, but attachment is not mechanically resolved.'],logic='(Moon OR L1) square/conjunction/opposition benevolent planet, “Retrograde”; retrograde referent retained unresolved.')
add('moon_sun_mars',[286,287],'grievous and mortall','danger',['Moon recedes from opposition of Sun.','Moon is swift.','Moon hastens to square OR opposition of Mars.'],'The disease will be grievous and mortal.',exceptions=['Same-time sextile or trine of Jupiter or Venus to Moon gives the explicit recovery branch on PDF287.'])
add('moon_jupiter_venus_exception',287,'the sick shall recover','recovery',['The preceding Moon receding from Sun’s opposition and hastening to Mars applies.','At the same time Moon salutes a sextile OR trine of Jupiter OR Venus.'],'The sick shall recover.',dependencies=['moon_sun_mars'])
add('usually_safe',287,'usually no danger','safety',['Moon is strong at time of the question.','Ascendant lord is free from misfortune.','Ascendant lord has no aspect to sixth lord.'],'There is usually no danger.')
add('question_moon_saturn',287,'an ill Omen','incipient_sickness',['At time of question Moon applies Saturn OR is impeded.'],'The source calls this an ill omen and sign of sickness at hand, and says the querent distrusts his own health, is sick, but does not know where to complain or in what bodily part the infirmity is placed.')
add('first_lying_moon',287,'a sign of ill','danger',['At first lying down, Moon is in the ascendant.','Moon is conjunct, square, OR opposite Saturn, Mars, OR another unfortunate planet.'],'It is a sign of ill and shows ill.',exceptions=['Unless Moon is in reception with the planet or planets so afflicting.'])
add('moon_fixed',287,'expect a long fit of sicknesse','duration',['At time of the question Moon is in a fixed sign.'],'Expect a long fit of sickness.')
add('moon_movable',287,'quick dispatch','duration',['At time of the question Moon is in a movable sign.'],'The source gives quick dispatch.')
add('moon_common',287,'somewhat long in curing','duration',['At time of the question Moon is in a common OR double-bodied sign.'],'The disease is not very difficult to cure, but somewhat long in curing.')
add('translation_dispositor',287,'great suspition','severity',['There is translation of light from the planet disposing Moon.','That dispositor is unfortunate.','The translation is to ascendant lord OR ascending sign.'],'It gives great suspicion of sharp sickness according to the nature of the signs and planets signifying the infirmity.',uncertainty=['The translating agent is not explicitly named in this construction.'])

section='Testimonies that the Querent shall live and not dye of the infirmity now afflicting'
add('survival_figure',287,'carefully have recourse','judgment_method',['It is seriously asked whether the querent will escape or live through the sickness currently suffered.'],'The reader must carefully return to the erected figure and observe the following rules.',uncertainty=['This is a source-defined procedural frame for the following testimonies.'])
add('moon_weak_male_strong_fortune',287,'restored to former health','recovery',['Moon separates from a malevolent, weak, ill-dignified planet.','Moon applies to a powerfully strong Fortune.'],'The sick party will be restored to former health.')
add('saturn_orient_cold',287,'it proceeding from Cold','recovery',['Saturn is oriental of Sun and significator of the disease.','The disease proceeds from cold, called Saturn’s unmixed true nature by the source.'],'The patient will recover.',uncertainty=['The source’s humoral and planetary premise is retained as historical content.'])
add('saturn_occ_heat',[287,288],'more of Heat then Cold','recovery',['In the like Saturn disease-significator case, Saturn is occidental.','General significators incline to or manifest disease more of heat than cold.'],'The sick will also recover.',uncertainty=['The following qualification nevertheless calls occidental Saturn unlucky; no override precedence is supplied.'],dependencies=['saturn_orient_cold'])
add('saturn_occ_unlucky',288,'yet you must ever understand','general_qualification',['Saturn is occidental.'],'The source says one must nevertheless understand Saturn is unlucky when occidental, etc.',uncertainty=['This is retained alongside the preceding conditional recovery rule, rather than used to erase it.','The etc. is not expanded.'],dependencies=['saturn_occ_heat'])
add('mars_orientation',288,'not so much to be feared','relative_severity',['Mars is after conjunction with Sun, identified here as occidental.'],'His evil influence is less to be feared than when he is oriental; the paragraph later repeats that oriental Mars does more hurt than occidental Mars.')
add('moon_mars_conj',288,'a strong sicknesse at hand','severity',['Moon is conjunct Mars.'],'This is dangerous and an argument of a strong sickness at hand.')
add('moon_mars_square_opposition',288,'doe lesse mischiefe','relative_severity',['Moon has opposition OR square aspect with Mars, in the comparison with conjunction.'],'These aspects do less mischief than the conjunction.',dependencies=['moon_mars_conj'])
add('moon_increase_hurt',288,'more hurt in her encrease','relative_severity',['Moon is increasing rather than decreasing, in the surrounding Moon/Mars discussion.'],'The source says Moon does more hurt in her increase than decrease.',uncertainty=['The surrounding Moon/Mars context is preserved; an unrestricted claim about every increasing Moon is not asserted.'],dependencies=['moon_mars_conj'])
add('reception_any',288,'after desperation','recovery',['Any reception occurs between ascendant lord and eighth lord.','Neither is infortunated by malignant planets.'],'After desperation there will be recovery.')
add('reception_house_triplicity',288,'perfectly recover','recovery',['Ascendant lord is in reception of eighth lord by house OR triplicity.','Fortunes assist with trine OR sextile of the ascending degree, sixth-house degree, OR Moon herself.'],'There is no danger of death and the sick will perfectly recover.',uncertainty=['The recipient phrase degree ... of sixt house is retained without silently assigning an extra geometric rule.'])
add('bene_l1_houses',288,'it prenotes sanity','recovery',['Ascendant lord is a benevolent planet.','He is in first, tenth, eleventh, fifth, OR third house.','He is not endangered by square OR opposition of malevolents.'],'It prenotes sanity or health, using the source’s historical wording.')
add('fortune_first_tenth',288,'first assailed the sicke person','recovery',['A Fortune is in midheaven OR first house.','The figure is for the time sickness first assailed the sick person.'],'This signifies likewise to the preceding sanity/health testimony.',dependencies=['bene_l1_houses'])
add('benefics_ascendant',288,'nothing is a more sure argument','recovery',['Sun, Jupiter, Venus, OR Moon is in the ascendant of the question.','The planet is not harmed by a hateful aspect of eighth OR sixth lord.'],'The source says nothing is a surer argument of health or that the sick shall live; it is more certain if these significators are in good signs: either house of Jupiter, Cancer, Leo, Libra, or Taurus.',uncertainty=['More certain is a source comparison, not a numeric probability.','The listed signs are historical conditions, not current clinical evidence.'])
add('moon_good_house',288,'she signifies health and life','recovery',['Moon is in her own house OR a house of Jupiter OR Venus.','There she is in the aspect of either Jupiter or Venus.','She is free from any ill aspect of Saturn OR Mars.'],'She signifies health and life.')
add('moon_jupiter_any',288,'a good argument of recovery','recovery',['Moon is conjunct Jupiter.'],'This is a good argument of recovery in whatever sign Jupiter is, but less in Capricorn than in any other sign. The source explains that neither Moon nor Jupiter delights there because it is Jupiter’s fall and Moon’s detriment.',exceptions=['Capricorn lessens the good signification; it is not rewritten as a total negation.'])
add('fall_strength',[288,289],'the strength of his influence','general_qualification',['A planet is in the sign wherein it falls.'],'The source says no planet delights there or can express the strength of its influence.',dependencies=['moon_jupiter_any'])
add('moon_apply_l1_good',289,'health and life are promised','recovery',['Moon applies to ascendant lord by trine OR sextile.','She is clear of all misfortune, OR not impeded especially by eighth OR sixth lord.'],'Health and life are promised.',uncertainty=['The printed or between freedom clauses is preserved rather than replaced by and.'],logic='C1 AND (clear of all misfortune OR not impeded especially by L8/L6), preserving printed OR.')
add('moon_succedent',289,'safety is also to be expected','safety',['Moon is well affected and in a succedent house.','She is increasing in light and motion.','She is not near Saturn’s or Mars’s bodies and not infected with their rays.'],'Safety is expected.',uncertainty=['No orb for near or infected with rays is supplied in this passage.'])
add('moon_house_list',289,'it doth argue life','recovery',['Moon is in first, tenth, eleventh, ninth, second, third, OR fifth.','Moon is trine OR sextile ascendant lord OR his antiscion.','Neither Moon nor ascendant lord has any other impediment.'],'It argues life even if the ascendant lord is a malevolent planet.')
add('moon_void_crisis',289,'a perfect Crisis','recovery',['At first falling sick Moon is void of course.','At her next crisis she meets sextile OR trine Jupiter OR Venus.','The aspect occurs in the very degree making a perfect crisis.'],'The sick shall recover, however much pained or grieved at time of asking the question or the source’s accesse of the Urine.',uncertainty=['Perfect crisis, next crisis, and its exact degree are not defined here.'])
add('start_free_aspects',289,'no feare or suspition','safety',['At first beginning or approach of disease, Sun, Moon, and ascendant lord are free from ill aspects of Infortunes OR eighth lord.'],'No fear or suspicion of the then sick party’s death need be made.')
add('bene_more_potent',289,'assured hopes of life','recovery',['Benevolent planets are more potent than malevolent planets.'],'They give assured hopes of life and invite the infirm person to confide in escape.',uncertainty=['The comparison is not assigned a numeric potency threshold.'])

section='Arguments of Death'
add('decumbiture_natal_seventh',289,'you may feare death','death_possibility',['The ascendant at first falling sick is the seventh house at birth.'],'One may fear death.',exceptions=['Unless that year’s profection is the same sign.'],uncertainty=['Profection is referred to the Treatise of Nativities, not defined here.','Historical natal/decumbiture cross-reference within this horary source, not a personal natal claim.'])
add('natal_adverse_signs',289,'adverse in a Nativity','source_list',['The source discusses signs adverse in a nativity.'],'The listed signs are those of the sixth, seventh, eighth, and twelfth.',dependencies=['decumbiture_natal_seventh'])
add('hylegical_oppressed',[289,290],'by a divine miracle as it were','death_testimony',['The five hylegical places at birth are oppressed at decumbiture.','The ascendant lord is also oppressed.'],'Judge death immediately to follow.',exceptions=['Unless reception intervenes between the Infortunes and the Fortunes interject comfortable aspects; then the sick may escape, by a divine miracle as it were.'],uncertainty=['The five hylegical places and exact oppression test are not defined in this passage.','The grammatical grouping of reception and Fortune intervention is not resolved into executable logic.'],logic='Oppression of five natal hylegical places at decumbiture AND L1 oppression; exception preserves source “unless reception ... and the Fortunes ...” wording without a definitive parse.')
add('planet_hour_heat_cold',290,'infinitely oppressed','severity',['A hot disease is first obtained in Mars’s hour, OR a cold disease in Saturn’s hour.'],'The person will be infinitely oppressed, in the source’s wording.',uncertainty=['Hot and cold retain historical source meaning.'])
add('combust_lords',290,'undoubtedly declare death','death_testimony',['The ascendant lord and lord of the figure are combust.'],'They undoubtedly declare death.',exceptions=['Unless there is some reception between Sun and them. With that reception and a fortunate Moon, after fear of danger a little hope remains, following the source’s own erratum (PDF888: read feare of danger).'],uncertainty=['Handwriting/strike-through obscures the original phrase. PDF888 identifies the deleted print as all hopes of escape and directs feare of danger; corrected and original layers are recorded separately.','Lord of the Figure is not identified by a selection algorithm in this passage.','Margin handwriting is not promoted to authorial printed text.'])
add('l1_moon_conj_l8',290,'threatens death','death_threat',['Ascendant lord and Moon are conjunct eighth lord.','No interposing aspects of the Fortunes occur.'],'This threatens death.')
add('l8_angle_l1_cadent',290,'is alwayes mortall','death_testimony',['Eighth lord is in an angle.','Ascendant lord is in a cadent house.'],'The source says this is always mortal, the rather if he is an Infortune.',uncertainty=['The pronoun he in the strengthening clause likely concerns eighth lord but is not resolved into an extra required condition.'])
add('moon_apply_eighth',290,'is alwayes dangerous','danger',['Moon applies to a planet in the eighth.'],'This is always dangerous.',uncertainty=['The source’s danger is not silently upgraded to certain death.'])
add('l1_apply_eighth',290,'the Moone being any manner','death_testimony',['Ascendant lord applies to eighth lord OR malevolent planets in the eighth.','Moon is corrupt in any manner.'],'This denotes death.')
add('moon_transfer_eighth',290,'brings usually death','death_testimony',['Moon transfers the light and influence of ascendant lord to eighth lord.'],'This usually brings death.')
add('l8_asc_afflicted',290,'being both afflicted','death_testimony',['Eighth lord is in ascendant.','Ascendant lord and Moon are both afflicted.'],'The source says likewise to the preceding usually-death testimony.',dependencies=['moon_transfer_eighth'],uncertainty=['The nearby usually is carried as the antecedent’s modality rather than silently strengthened to always.'])
add('l1_eighth_weak_moon',290,'It also proves fatall','death_testimony',['Ascendant lord is unfortunate in eighth.','Moon is corrupted OR very weak, and in no essential dignity.'],'This also proves fatal.',uncertainty=['The scope of no essential dignity over the corrupted/very-weak alternative is not fully explicit.'],logic='L1 unfortunate in eighth; Moon “corrupted or very weak, and in no essential Dignity”; preserve alternative and conjunctive phrase without forcing scope.')
add('subterranean_eighth',290,'being Subterranean','death_testimony',['Ascendant lord is subterranean.','He has any aspect to eighth lord in eighth.'],'This argues death.')
add('both_fourth',290,'argue death','death_testimony',['Ascendant lord is in fourth.','Eighth lord is in fourth.','They are conjunct.'],'This argues death.',uncertainty=[])
add('l1_joined_bad_lords',290,'it seldome succeeds well','adverse_outcome',['Ascendant lord is corporally joined to fourth, sixth, seventh, OR twelfth lord.'],'This is a very ill sign of life; it seldom succeeds well with the sick person.',uncertainty=['Seldom succeeds well is not converted into inevitable death.'])
add('luminary_time',290,'Luminary of the time','judgment_method',['Judging these illness testimonies.'],'The source directs special consideration of the luminary of the time; according to its good or ill condition one may improve judgment.',uncertainty=['No numeric weighting or override rule is supplied here.'])
add('evil_eighth_peril',[290,291],'great peril of death','death_danger',['Ascendant lord is afflicted by an evil planet in eighth.','No benevolent aspect of Fortunes occurs.','Moon is also vitiated.'],'The source shows great peril of death, usually attributing it to ill government of the sick party or some error in ordering and course of physic.',uncertainty=['The historical blame/treatment attribution is not evidence of actual patient conduct or treatment efficacy.'])
add('first_question_combust',291,'a powerfull argument','death_testimony',['At the first question to the physician, ascendant lord is combust in ascendant.'],'This is a powerful argument that the sick party will die.')
add('l1_l8_unfortunate',291,'prenote death','death_testimony',['Ascendant lord and eighth lord are unfortunate.'],'They prenote death.')
add('l8_tenth',291,'in the tenth house','death_testimony',['Eighth lord is in tenth.','Ascendant lord is in fourth, sixth, OR seventh, afflicted by malevolent planets.'],'These argue death.')
add('hour_eighth_asc',291,'Lord of the houre','death_testimony',['A planet is very strong and in ascendant.','That planet is lord of the hour and of eighth.'],'It portends death.',uncertainty=['Very strong is not assigned a numeric threshold here.'])
add('l8_retro_moon',291,'it shewes death','death_testimony',['Eighth lord is retrograde.','Eighth lord is conjunct, square, OR opposite Moon.'],'It shows death.')
add('l8_seventh_cadent',291,'and more certaine','death_testimony',['Eighth lord is in seventh.','Moon and ascendant lord are cadent and infected with ill aspects of Infortunes.'],'This is a death testimony in the section’s sequence, more certain if one malevolent is eighth lord or is in eighth.',uncertainty=['The sentence omits an independent finite outcome before its certainty clause; outcome is inherited from local death-argument context.'])
add('some_say_saturn_jupiter',291,'some say','attributed_variant',['Moon is conjunct Saturn OR Jupiter.'],'Some say the sickness receives little good thereby and the sick will not escape.',exceptions=['Unless Saturn is retrograde AND Jupiter direct.'],uncertainty=['The printed or and the exception naming both planets are retained.','This attributed variant is not reconciled by deleting the distinct Jupiter-recovery testimony.'],dependencies=['moon_jupiter_any'],attribution='Lilly reporting “some say”; named authority unspecified')
add('l1_eighth_reception',291,'probable the sick will dye','death_probability',['Ascendant lord is conjunct eighth lord, OR square/conjunct a planet in eighth, OR in eighth lord’s antiscion.','The benevolent sextile OR trine of Jupiter is absent.','Moon is in any way afflicted at the same time.'],'It is probable the sick will die.',exceptions=['If ascendant lord is in reception with the planet in eighth, escape from death is possible; however, a very long and grievous disease cannot be avoided.'],uncertainty=['Reception exception refers to a planet in eighth; its scope over every earlier alternative is not fully restated.','Source probability is qualitative, not a numerical estimate.'])
add('moon_saturn_mars_death',291,'one argument','death_testimony',['Moon is with Saturn OR Mars.','Good aspect assistance from Jupiter and Venus is absent.'],'This is one argument the sick will die then; Saturn being slow or going retrograde makes it worse, and other concurrent testimonies make it more certain.',uncertainty=['The text says from Jupiter and Venus; whether either assistance suffices or both are required is not converted into an executable choice.','The and-if Saturn escalation remains additional rather than silently required in the Mars branch.'],logic='Moon with Saturn/Mars; absence of source-stated Jupiter-and-Venus assistance; IF Saturn slow/retrograde then worse; IF other testimonies concur then more certain.')
add('l1_seventh_fall',291,'these are testimonies of death','death_testimony',['Ascendant lord is in seventh, in his fall, OR under earth in fourth or sixth, OR other cadent houses, afflicted by malevolents.','Eighth lord is in seventh.'],'These are testimonies of death.',uncertainty=['Punctuation does not settle whether in seventh and in his fall are conjunctive, or how affliction scopes over the place alternatives.'],logic='Source sequence: L1 in seventh, in fall, or under earth in fourth/sixth, or other cadents, afflicted by malevolents; AND L8 in seventh. Exact grouping unresolved.')
add('violent_stars',[291,292],'a violent fixed Starre','death_testimony',['A malevolent planet is near the ascending degree, OR a violent fixed star is there.','The source’s examples are Antares in the fourth degree of Sagittarius, Lans/Lanx Australis about the ninth of Scorpio, Palilicium in four Gemini, and Caput Medusae in twenty Taurus.'],'These prenote death.',uncertainty=['Near is not given an orb.','The name printed as Lans/Lanx Australis is not silently corrected; identity spelling remains a paleographic uncertainty.','The stated degrees are historical source coordinates, not present-day positions.','The star list supplies examples rather than an additional requirement that every star be present.'],logic='Malevolent near ascending degree OR violent fixed star there; historical example list is descriptive, not an AND condition.')
add('l1_leo_aquarius',292,'little hopes of recovery','low_recovery_hope',['Ascendant lord is in Leo OR Aquarius.','He is in any bad configuration of sixth OR twelfth lord.'],'This shows little hope of recovery.')
add('lights_saturn_angles',292,'a tedious long sicknesse','duration',['Both Lights are afflicted by Saturn in angles.'],'They testify to a tedious long sickness.',uncertainty=['The angular phrase’s exact attachment is not fully explicit.'])
add('lights_underground',292,'under the earth','duration',['Both Lights are ill dignified and under earth.'],'They signify the same tedious long sickness.',dependencies=['lights_saturn_angles'])
add('sun_afflicted_begin',292,'an extraordinary long sicknesse','death_or_duration',['From the disease’s beginning Sun is corporally afflicted, OR impeded by Saturn/Mars square/opposition, OR in perfect antiscion of a malignant planet, OR applies and does not separate.'],'Either death or extraordinarily long sickness succeeds.',uncertainty=['The target of applying and not separating is not restated; exact scope over preceding alternatives remains unresolved.'],logic='Beginning-of-disease Sun condition: bodily affliction OR Saturn/Mars square/opposition OR perfect antiscion of malignant OR applies-not-separates; last alternative’s object/scope unresolved.')
add('moon_opp_l1',292,'not easily curable','death_or_severity',['After disease begins Moon comes to opposition of ascendant lord.','Ascendant lord is retrograde OR combust.'],'This argues death OR a sharp disease not easily curable.')
add('saturn_l8_moon_list',292,'are arguments of death','death_testimony',['Saturn is opposite eighth lord.','Moon is in fourth with Mars, OR Moon is in ascendant and near the ascending degree.'],'The printed configuration sequence is called arguments of death.',uncertainty=['The source may list distinct testimonies or require a combined sequence; it is not normalized into independent unconditional rules.','Near is unquantified.'],logic='Unresolved source list: Saturn opposite L8, Moon in fourth with Mars, OR Moon in ascendant AND near ascending degree; conjunctive/list scope unresolved.')
add('moon_besieged',292,'ill Omens of health','danger',['Moon is besieged by Infortunes, OR between Sun and Mars, OR between Sun and Saturn.'],'These are ill omens of health.',uncertainty=['Besiegement is not assigned a numeric span in this passage.'])
add('beams_departing',292,'departing from Combustion','staged_progression',['The person falls sick while Moon is under Sun’s beams, identified here as departing combustion.'],'The disease shall increase until Moon has passed Sun’s opposition. If Moon then proves ill affected and comes to an ill aspect of eighth lord, it threatens death; otherwise the person escapes.',exceptions=['After the specified stage, absence of the ill-affected/ill-eighth-aspect branch yields the explicit escape alternative.'],uncertainty=['No orb for beams/combustion or ill aspect is supplied in this passage.'],logic='At onset Moon under beams/departing combustion -> increase until passed Sun opposition; THEN IF Moon ill affected AND comes to ill aspect of L8 -> threatens death; ELSE escape.')
add('sixth_final_danger',292,'shew great danger','danger',['Any malevolent is in sixth, OR any planet is peregrine AND unfortunate in sixth.'],'These show great danger in the disease.')
add('moon_combust_eighth_stars',292,'the Pleiades in 24','death_testimony',['The source sequence begins Moon’s combustion in eighth house, and in Leo, or in Libra.','It continues square OR opposition to Saturn OR Mercury, OR conjunction with Pleiades in 24 Taurus OR other violent fixed stars.'],'The source calls the sequence an argument of death.',uncertainty=['A strict conjunction of all clauses would conflict with the listed alternative sign positions; exact AND/OR grouping remains unresolved.','Mercury’s printed glyph is visually verified and is not replaced by Mars.','The Pleiades coordinate is the historical source value, not a current coordinate.'],logic='Preserve sequence without executable resolution: combustion of Moon in eighth AND in Leo OR Libra, square/opposition Saturn OR Mercury, OR conjunction Pleiades at 24 Taurus OR other violent stars.')
add('moon_lady_combust_l8',292,'shew death','death_testimony',['Moon is lady of sixth OR ascendant and is in combustion.','At the same time eighth lord is afflicted by conjunction OR ill aspect of Saturn OR Mars.'],'These show death. This is the final included sentence before DARIOT Abridged.',uncertainty=['Combustion is read as applying to Moon in the lordship alternatives; no numeric combustion threshold is imported.'])

for row in rules:
    row['dependencies']=[aliases.get(x,x) for x in row['dependencies']]
layers = {
    'bene_l1_houses': {
        'original_print': 'The word is broken after pla- at the end of printed line 18; the start of line 19 appears ted with an overmark at its first character.',
        'handwriting': 'An overmark at the broken word is visible; its hand/authority is not identified.',
        'authorial_errata': {'pdf_page':888,'visible_label':'ERRATA','target':'p 254 l 18 & 19','instruction':'r placed'},
        'admitted_reading': 'placed; positional condition is retained. The correction is explicitly sourced to the errata.'
    },
    'combust_lords': {
        'original_print': 'The phrase following after is crossed/overwritten and not wholly readable by this reader. The errata identifies the deleted phrase as all hopes of escape.',
        'handwriting': 'Striking/overwriting occurs over the phrase; a margin annotation appears to contain ear of danger. It is not attributed to Lilly or treated as the correction authority.',
        'authorial_errata': {'pdf_page':888,'visible_label':'ERRATA','target':'p 256 l 8','instruction':'dele all hopes of escape, r. feare of danger'},
        'admitted_reading': 'With the stated reception and fortunate Moon, after feare of danger a little hopes remaines. This is the corrected reading, not a claim that the overwritten original line was fully legible.'
    },
    'l1_eighth_reception': {
        'original_print': 'The Antiscion phrase visibly concerns the Lord of the eight followed by an overmarked terminal character.',
        'handwriting': 'An overmark on the terminal character is visible and not assigned authorial authority.',
        'authorial_errata': {'pdf_page':888,'visible_label':'ERRATA','target':'p 257 l 23','instruction':'r eight'},
        'admitted_reading': 'The eighth lord; source errata is preserved as a separate spelling/reading correction.'
    }
}
for key,layer in layers.items():
    row=next(r for r in rules if r['id']==aliases[key])
    row['source_layers']=layer

(ROOT/'CANDIDATE_RULES.json').write_text(json.dumps(rules,ensure_ascii=False,indent=2)+'\n')
(ROOT/'CANDIDATE_ALIAS_MAP.json').write_text(json.dumps(aliases,indent=2)+'\n')

groups=[
    (283,'Opening continuation after A-owned Pisces sentence','If the Moon apply by ill aspect','if a woman ask','moon_ill_l1','venus_woman'),
    (283,'Remaining body paragraph','If the Lord of the sixt apply','threatens great','l6_applies_l1','male6_danger'),
    (284,'Top carryover and fortified/benevolent qualifiers','danger in the Sicknesse','will be permanent','male6_danger','bene6_not_author'),
    (284,'Long body paragraph to recovery carryover','Many times it happens','Lord of the twelfth','witch_suspicion','unafflicted_recovery'),
    (285,'Top carryover and first paragraph','sixt or eighth','otherwise qualified','unafflicted_recovery','saturn_l1_slow'),
    (285,'Angular/motion/affliction paragraph','The Lord of the ascendant in an Angle','so doth also the Moon','l1_angle_safe','slow_moon'),
    (286,'Moon carryover paragraph','when she is slow in motion','look for the contrary','slow_moon','moon_retro_occ'),
    (286,'Scorpio/luminaries/Mars paragraph','When you find Scorpio ascending','no great danger','scorpio_blame','mars_l1_venus'),
    (286,'Sixth lord and Moon adverse paragraph','If the Lord of the sixt be Combust','at the same','l6_death_doubt','moon_sun_mars'),
    (287,'Top continuation and usually/no-danger alternatives','same time','the infirmity is placed','moon_sun_mars','question_moon_saturn'),
    (287,'First lying down/Moon signs/translation','At the time of ones first lying down','signifying the infirmity','first_lying_moon','translation_dispositor'),
    (287,'Survival heading and opening paragraph','When it is demanded seriously','recovered','survival_figure','saturn_occ_heat'),
    (288,'Top survival continuation and Mars comparison','yet you must ever understand','Occidentall','saturn_occ_heat','moon_increase_hurt'),
    (288,'Reception and benefic place paragraph','When you find there is any reception','health and life','reception_any','moon_good_house'),
    (288,'Moon/Jupiter and fall maxim carryover','a good argument of recovery','able','moon_jupiter_any','fall_strength'),
    (289,'Fall maxim carryover and Moon configurations','able therein to expresse','it doth argue life','fall_strength','moon_house_list'),
    (289,'Void of course/crisis/onset/relative potency','When at the first falling sick','confide of his escape','moon_void_crisis','bene_more_potent'),
    (289,'Arguments of Death heading and natal/profection paragraph','When the ascendant at time of first falling sick','and twelfth','decumbiture_natal_seventh','natal_adverse_signs'),
    (289,'Five hylegical places paragraph','When the five Hylegicall places','interject their','hylegical_oppressed','hylegical_oppressed'),
    (290,'Hylegical exception carryover','their comfortable aspects','the party sick may escape','hylegical_oppressed','hylegical_oppressed'),
    (290,'Planetary hour sentence','He will be infinitely oppressed','a cold one','planet_hour_heat_cold','planet_hour_heat_cold'),
    (290,'Combust lords and reception/fortunate Moon','The Lord of the ascendant and of the Figure Combust','a little hopes remaines','combust_lords','combust_lords'),
    (290,'Conjunction eighth lord','The Lord of the ascendant and the Moon','threatens death','l1_moon_conj_l8','l1_moon_conj_l8'),
    (290,'Angular eighth lord','The Lord of the eighth in an Angle','Infortune','l8_angle_l1_cadent','l8_angle_l1_cadent'),
    (290,'Applications to eighth','The application of the Moon','denotes death','moon_apply_eighth','l1_apply_eighth'),
    (290,'Transfer, placements, conjunctions','The Moon transferring','sick person then','moon_transfer_eighth','l1_joined_bad_lords'),
    (290,'Luminary of time and peril carryover','Have speciall consideration','usually','luminary_time','evil_eighth_peril'),
    (291,'Peril attribution carryover and first question','usually by reason','Combust in the ascendant','evil_eighth_peril','first_question_combust'),
    (291,'Unfortunate lords','The Lord of the ascendant and of the eighth unfortunate','prenote death','l1_l8_unfortunate','l1_l8_unfortunate'),
    (291,'Eighth lord tenth','The Lord of the eighth in the tenth house','argue death','l8_tenth','l8_tenth'),
    (291,'Hour lord/retrograde/cadents/some say','A Planet very strong','Jupiter Direct','hour_eighth_asc','some_say_saturn_jupiter'),
    (291,'Aspect/reception/Moon/placement/star sequence','When the Lord of the Ascendant','Caput Medusae','l1_eighth_reception','violent_stars'),
    (292,'Star carryover to staged Moon rule','in twenty Taurus','otherwise he or she will escape','violent_stars','beams_departing'),
    (292,'Final complete included paragraph','Any malevolent in the sixt','shew death','sixth_final_danger','moon_lady_combust_l8')
]
def ids_between(first,last):
    lo=int(aliases[first][1:]); hi=int(aliases[last][1:])
    return [f'B{i:03d}' for i in range(lo,hi+1)]
coverage={
    'schema':'b02k.section_coverage.v1','reader':'B','chapter':'XLIV',
    'scope':'historical horary source only',
    'source_pdf_sha256':frozen['source_pdf_sha256'],
    'source_first_notes_sha256':frozen['source_notes']['sha256'],
    'independence':'Original pages read and source notes frozen before candidate creation; no B02j schema or prior candidate extraction consulted.',
    'boundary':frozen['boundary'],
    'boundary_refinement':'Reader A owns the complete common-sign/Pisces sentence across PDF282–283. Reader B starts at the next Moon ill-aspect rule; no duplicate Pisces candidate.',
    'excluded':[{'pdf_page':292,'starts_at':'DARIOT Abridged.','reason':'Admitted boundary excludes the heading, introduction, and all following Dariot material.'}],
    'supplementary_source_pages':[{'pdf_page':888,'visible_label':'ERRATA','role':'Source-authored errata for printed pages 254, 256, 257 only; inspected after source-first freeze.'}],
    'anchor_policy':'Anchor phrases use ordinary s for long-s and join line/page-break words; glyph names are expanded in paraphrase/conditions, not invented as exact quoted words. Coverage locator labels are descriptive navigation aids, not certified quotations.',
    'sections':[{'section':s,'candidate_ids':[r['id'] for r in rules if r['section']==s],'candidate_count':sum(r['section']==s for r in rules)} for s in dict.fromkeys(r['section'] for r in rules)],
    'page_coverage':[{'pdf_page':p,'visible_printed_label':str(p-34),'original_full_page_viewed':True,'candidate_ids':[r['id'] for r in rules if p in r['pdf_pages']]} for p in range(283,293)],
    'paragraph_coverage':[{'pdf_page':p,'visible_printed_label':str(p-34),'region':name,'start_locator':start,'end_locator':end,'candidate_ids':ids_between(first,last)} for p,name,start,end,first,last in groups],
    'reader_coverage_assessment':'Every observed rule, qualifier, source list, and judgment instruction in the assigned span is represented by the paragraph mapping, subject to typed unresolved readings and root integration/review. This is not a claim of clinical validity or an executable rule set.',
    'candidate_count':len(rules),
    'all_condition_logic_executable':False,
    'source_variants_preserved':[['B061','B062'],['B073','B104'],['B049','B050']],
    'cross_page_dependencies':[{'pages':[282,283],'owner':'reader A','description':'Common-sign/Pisces sentence; B context only.'}]+[{'candidate_id':r['id'],'pages':r['pdf_pages']} for r in rules if len(r['pdf_pages'])>1]
}
(ROOT/'SECTION_COVERAGE.json').write_text(json.dumps(coverage,ensure_ascii=False,indent=2)+'\n')

issues=[]
def issue(kind,source,gap,keys,disposition='Retain source wording/alternatives; no executable interpretation admitted.',origin='assistant_identified_gap',status='open'):
    ids=[aliases[k] for k in keys]
    pages=sorted({p for r in rules if r['id'] in ids for p in r['pdf_pages']})
    issues.append({'id':f'U-B{len(issues)+1:02d}','type':kind,'origin':origin,'status':status,'source_defined_content':source,'assistant_identified_gap':gap,'affected_candidate_ids':ids,'pdf_pages':pages,'disposition':disposition})
issue('lexical_or_source_tension','The sixth/eighth exchange with sextile/trine says not doubt of the death, then explains Nature is not overcome and the sick shall overcome it.','The historical sense of doubt or textual inconsistency is not settled by this reading.',['six_eight_swap'])
issue('conditional_scope','The Venus/Scorpio clause and female-question branch follow the Moon-sixth/ill-Venus condition; the source uses etc.','Which earlier conditions persist into each branch, and what etc. expands, remain unresolved.',['venus_scorpio','venus_woman'])
issue('timing_unit_selection','The source maps remaining sign-exit degrees to as many months, weeks, or days according to sign nature and quality.','This passage does not choose a determinate unit or rounding rule. This is an absence only within this passage, not a whole-book absence claim.',['exit_timing'],origin='source_defined_content')
issue('compound_condition_grouping','Several long sentences combine commas, and, or, and shifting pronouns.','Exact grouping of the listed factors is not consistently determined by the punctuation.',['l6_complex_worsening','one_six_exit_death','azimene','unafflicted_recovery','l1_bad_relapse','swift_moon','l1_eighth_weak_moon','l1_eighth_reception','moon_saturn_mars_death','l1_seventh_fall','lights_saturn_angles','sun_afflicted_begin','moon_lady_combust_l8'])
issue('motion_reference_value','Moon’s slowness is defined relative to mean motion over twenty-four hours.','No numerical mean motion is stated in this passage; do not import a threshold.',['slow_moon'])
issue('qualitative_strength_and_distance','The source uses powerfully, strong, weaker, more strongly dignified, more potent, near, or rays.','No numeric scoring, comparative cutoff, or orb for these words is supplied at these points. Any operational specification would be an additional dependency.',['male6_fortified','bene6_not_author','powerful_affliction','fortunes_assist','moon_weak_male_strong_fortune','benefics_ascendant','moon_succedent','bene_more_potent','hour_eighth_asc','violent_stars','saturn_l8_moon_list','moon_besieged'])
issue('technical_definition_dependency','The source invokes Azimene degrees, benevolent house of heaven, translation of light, crisis, profection, five hylegical places, and lord of the figure.','These specific passages do not supply a complete definition/selection algorithm. No absence claim about the entire book is made.',['azimene','l1_angle_safe','translation_dispositor','moon_void_crisis','decumbiture_natal_seventh','hylegical_oppressed','combust_lords'])
issue('grammatical_referent','Retrograde immediately follows a benevolent planet in a Moon-or-ascendant-lord aspect sentence.','The nearest reading is the benevolent planet, but attachment is not fixed as executable interpretation.',['retro_bene_recovery'])
issue('variant_preservation','One conditional occidental-Saturn disease rule gives recovery; the next clause nevertheless calls occidental Saturn unlucky.','No explicit precedence rule combines these different-scope statements.',['saturn_occ_heat','saturn_occ_unlucky'],'Retain both conditional recovery and general qualification; do not manufacture contradiction or override.',origin='source_defined_content')
issue('attributed_variant','Moon conjunct Jupiter is elsewhere a good recovery argument; some say Moon conjunct Saturn or Jupiter gives no escape unless Saturn retrograde and Jupiter direct.','The anonymous attribution and interaction of the printed or with the two-planet exception are not resolved.',['moon_jupiter_any','some_say_saturn_jupiter'],'Retain the attributed variant and independent Jupiter-recovery rule, with no invented precedence.',origin='source_defined_content')
issue('contextual_scope','Moon doing more hurt in increase appears in a Moon/Mars comparison, while the succedent Moon safety condition explicitly requires increasing light/motion.','The comparison must not be widened into an unrestricted adverse rule for every increasing Moon.',['moon_increase_hurt','moon_succedent'],'Preserve local context and both source conditions; neither is silently an unconditional override.')
issue('hylegical_exception_grouping','The source says unless reception intervenes between Infortunes, and Fortunes interject comfortable aspects, then escape may occur as by a divine miracle.','Exact AND/OR scope of the exception is not settled for formal application.',['hylegical_oppressed'])
issue('obscured_original_with_source_erratum','PDF290 contains crossed/overwritten print. PDF888 identifies all hopes of escape for deletion and gives feare of danger.','The original obscured phrase is not completely directly legible; the handwriting’s author and authority are unknown.',['combust_lords'],'Use the source-authored erratum for the corrected reading while retaining original/handwriting/errata separately. The corrected reading is settled; original-layer paleography remains open.')
issue('fixed_star_paleography_and_epoch','The star list gives Antares, Lans/Lanx Australis, Palilicium, Caput Medusae, and historical degree/sign values.','The Lans/Lanx spelling and the exact proximity threshold remain open; no current epoch coordinates are inferred.',['violent_stars'])
issue('listed_or_combined_testimonies','Saturn opposite eighth lord is followed by Moon fourth with Mars, or Moon ascendant near rising degree.','It is unresolved whether these are separate testimonies or one combined configuration with alternatives.',['saturn_l8_moon_list'])
issue('alternative_sign_and_aspect_grouping','The final combustion rule lists eighth house, Leo or Libra, square/opposition Saturn or Mercury, and Pleiades at 24 Taurus or other violent stars.','The exact grouping cannot be forced into one all-conjunctive condition because the sign positions may be alternative branches.',['moon_combust_eighth_stars'],'Preserve all listed clauses with unresolved grouping and executable=false. Mercury is visually verified, not an unresolved Mars alternative.')
issue('historical_evidence_class','The source makes moral, sexual, supernatural, and treatment-effect attributions.','These general historical assertions are not independently verified clinical examples; the extraction cannot supply modern diagnostic or individual-person claims.',['venus_self_blame','venus_scorpio','venus_woman','jupiter_medicines','male6_fortified','witch_suspicion','scorpio_blame','evil_eighth_peril'],'Keep historical attribution, exact scope, and no executable/clinical inference. This is an evidence-class boundary, not a proposed correction of source content.')
issue('source_errata_layer','PDF888 directs p254 lines18–19 read placed and p257 line23 read eight.','Overmarked or faulty original characters should not be silently conflated with their source-authored correction.',['bene_l1_houses','l1_eighth_reception'],'Correction admitted with explicit original/handwriting/errata layers; no unresolved substantive effect on the respective placement/eighth-lord conditions.',origin='source_defined_content',status='resolved_with_separate_layers')
(ROOT/'UNRESOLVED.json').write_text(json.dumps(issues,ensure_ascii=False,indent=2)+'\n')

print(json.dumps({'count':len(rules),'first':rules[0]['id'],'last':rules[-1]['id'],'by_section':{s:sum(r['section']==s for r in rules) for s in dict.fromkeys(r['section'] for r in rules)}}))
